### ISSUE TITLE
Wrong highlighting area in galen report if test launched on device with "device pixel ratio" > 1

### ISSUE THREAD

**Issue by kmamaev** [galenframework/galen#102]
If a galen test is launched on real android device with "device pixel ratio" > 1 (e.g. Nexus 5 where devicePixelRatio = 3) highlighting areas in report don't match locations of appropriate elements on screenshot.
![image](https://cloud.githubusercontent.com/assets/5500262/4454171/7d028106-486b-11e4-9cff-f56f7d375f72.png)
We are using Galen java API. Would you please provide a possibility to preset device pixel ratio manually in code (for example via webdriver capabilities) which value will be as multiplier of coordinates of elements.

**Comment by saikrishna321** [comment]
@ishubin i ran the tests on Appium IOS simulator, i'm having a failure tests so that i was expecting the report with simulator screenshot. But i see empty report only for test running on IOS Simulator. 

Note : I see the test getting executed on simulator. Can you please tell me where i'm going wrong ?

Galen JAVA API version 2.0 with TestNG and Appium latest

**Comment by ishubin** [comment]
@saikrishna321 I am sorry but I have no experience running Galen in IOS simulator. Curious to know how you managed to run it there :)
I was only able to run it on Android real phone and tablet

**Comment by saikrishna321** [comment]
@ishubin I just started the Appium server and added the below caps 

DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", "iPhone 6");
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("platformVersion", "8.4");
        capabilities.setCapability("browserName", "safari");
        driver = new IOSDriver<WebElement>(new URL("http://127.0.0.1:4723/wd/hub"),
                capabilities);

This launches the Safari on IOS Simulator and runs the web.

**Comment by saikrishna321** [comment]
@ishubin  btw how have u executed it on android phone and tablet ?

**Comment by ishubin** [comment]
@saikrishna321 Here is the video where I explain that https://www.youtube.com/watch?v=zmbqTe0aUtc

**Comment by saikrishna321** [comment]
@ishubin  i tried it with appium java.. the test runs but when capturing screenshot it fails .. 

https://gist.github.com/saikrishna321/f9e79c30859441541d54 (GalenTestBase.java)

https://gist.github.com/saikrishna321/c698ebb74cfab15822af (error stack )

[main] ERROR com.galenframework.api.Galen - Error during setting screenshot.
java.lang.RuntimeException: Error making screenshot
	at com.galenframework.browser.SeleniumBrowser.createScreenshot(SeleniumBrowser.java:96)
	at com.galenframework.page.selenium.SeleniumPage.createScreenshot(SeleniumPage.java:171)

**Comment by saikrishna321** [comment]
@ishubin  can u help me on this pls

**Comment by ishubin** [comment]
@saikrishna321 I am sorry I can't help you with that. I also had similar issues with different android devices and versions on SauceLabs. I don't know how to solve this issue.

**Comment by saikrishna321** [comment]
@ishubin okie thanks.. i got it working on ios simulator but wrong area is highlighted.

<img width="1153" alt="screen shot 2015-08-24 at 2 50 26 pm" src="https://cloud.githubusercontent.com/assets/4045041/9436781/7581c1e2-4a6f-11e5-8a28-93ec49a8a24a.png">

**Comment by ishubin** [comment]
@saikrishna321 It is not only the incorrect area highlighted. It is just the completely incorrect area used in validations as well. I am not sure what's going on with this stupid ios simulator, but I had exactly the same problem in the latest ios versions. It seems like it is completely useless for layout testing as it gives incorrect locations of elements. The only version that worked well was ios 6.0.

**Comment by saikrishna321** [comment]
@ishubin  could this b something to do the retina display ? 

Let me try running this on real iOS device n see how it works .. will keep u posted soon .

**Comment by saikrishna321** [comment]
@ishubin i tried it running on iOS real device, its still the same(iPhone 5C)
<img width="1146" alt="screen shot 2015-08-25 at 2 29 10 pm" src="https://cloud.githubusercontent.com/assets/4045041/9462812/da2a50de-4b35-11e5-9af9-52f17d8175f9.png">

**Comment by ishubin** [comment]
@saikrishna321 Well we can't do anything with that. Its all up to the appium team

**Comment by ovenal** [comment]
hi @ishubin 
Galen is really great tool and we are going to use it to test responsive design on real mobile devices. During the running of our tests on BrowserStack we faced with a problem which is being discussed here. In one [article] (http://mindengine.net/post/2013-11-16-tdd-for-responsive-design-or-how-to-automate-testing-of-website-layout-for-different-devices/#.VfazApdGRL4) you mentioned that there was an issue in WebDriver with getting locations and dimensions on mobile (). This discussion is also about the same issue. 
Do you know if this issue in WebDriver is documented (i.e. an issue in WebDriver's bugtracker)? 
I googled a bit but couldn't find any mentions about it.

**Comment by ishubin** [comment]
@ovenal No, I don't know if it is documented anywhere. From my own experience all android devices worked fine. But on SauceLabs for iphone and ipad it gave incorrect locations if iOS version was greater then 6

**Comment by jfernandogt** [comment]
Hello,

I have the same error on android, iphone and ipad devices (I am using this repo: https://github.com/ArtyomAnohin/galen-saucelabs-test)

When I am comparing images or view the report I get the same error:

![image](https://cloud.githubusercontent.com/assets/7839474/26422574/aac2b0ea-4087-11e7-954a-9b4cb1e5e5f5.png)


![image](https://cloud.githubusercontent.com/assets/7839474/26422602/bf903646-4087-11e7-9fda-ef0aaca65b54.png)


Does anyone have a solution?

**Comment by ArtyomAnohin** [comment]
@jfernandogt @ishubin 
Hi all.
Perhaps the reason is site uses Scroll Pagination with AJAX. So DOM ready when page load, but bloks displayed when user scroll page.

@jfernandogt as for 2nd image - please add more details. What result do you expect or what spec code do you use?

**Comment by hypery2k** [comment]
Did you tried disabling full page screenshots?
