### ISSUE TITLE
Need a way to add notes to reports on a per spec basis

### ISSUE THREAD

**Issue by erquhart** [galenframework/galen#108]
For example, I'm currently on a project where the design specification measures vertical distance between text and an object above the text based on the text's x-height (the top edge of a lowercase letter). Galen can't measure that way, so I need to subtract the distance between the x-height and the top of the text element from the distance defined in the design spec:

```
@ Home | mobile
--------------------------------------------------------
section-header
  # x-height comp, changed from 48px to 42px
  below: widget-shelf 42px
```

Ideally, that "x-height comp" bit would show up in the report right along with the results from this particular spec - that way we can pass a report to our QA team and, when compared to the design spec, they can see that in this instance, 42px is equivalent to 48px.

Possible?

**Comment by ishubin** [comment]
Implemented in release-1.6 branch.
The way it works is by using a sentence with double-quotes before actual spec
```
login-button
    "It should have normal height"  height: 50 to 70px
```
