### ISSUE TITLE
Adding building JUnit/TestNG runners

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#117]
Would be helpful to already include abstract classes or runners for TestNG and JUnit.

I've created an sample project: https://github.com/hypery2k/galen_samples

**Comment by hypery2k** [comment]
I currently experimenting with some runner samples for TestNG and JUnit. The base code can also used for a maven plugin

**Comment by hypery2k** [comment]
I've added some basic JUnit and TestNG runner's on my fork. Can you please review it, before I continue with my work. For both test frameworks I've created a BootstrapIT sample test to you how it be used:

**TestNG**
```java

@Listeners(value = GalenListener.class)
public class BootstrapIT {

    @Inject
    private GalenExecutor runner;

    @Test
    public void oneTest() throws Exception {
        runner.checkLayout(new TestDevice("small-phone", new Dimension(280, 800), asList("small-phone", "phone", "mobile")), "http://getbootstrap.com/css/",
                "/src/test/resources/specs/bootstrap/commonLayout.spec", null);
    }
```


**JUnit**
```java
@RunWith(GalenRunner.class)
public class BootstrapIT {

    @Inject
    private GalenExecutor runner;

    @Test
    public void oneTest() throws Exception {
        runner.checkLayout(new TestDevice("small-phone", new Dimension(280, 800), asList("small-phone", "phone", "mobile")), "http://getbootstrap.com/css/",
                "/specs/bootstrap/commonLayout.spec", null);
    }
```

What do you think about it?

**Comment by ishubin** [comment]
It looks nice for simple page validation. But what if I need to perform some actions on the page before checking its layout? In case of these JUnit and TestNG runners I would rather go for the simplest solution possible and just let users use the existent Java API. The idea is that they have to manage the WebDriver themselves and pass it to checkLayout method.

**Comment by hypery2k** [comment]
my created API allows also driver interaction and customization. Just see my latest comment and think about it. I personally like the idea that also Java developer have a ready to use API and if there is a need for customization they can use it, see my example test

**Comment by ishubin** [comment]
@hypery2k I agree with you on having ready to use API. The reason I am asking these questions is that I am concerned about the increase of functionality in Galen. Anything that is added to the API will have to be maintained over all versions. I am not in favor of changing API too often that is why I prefer to have the most simplest code that is extendable and is not limiting users. But lets see how it goes.
