### ISSUE TITLE
Test groups

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#119]
1. Test should belong to multiple groups (standard runner, javascript tests)
2. Html report overview should show groups and tests lists
3. Should run specified group ```galen test . --groups "Group1, Group2, Group3"```
4. Should run excluded group ```galen test . --excludeGroups "Group1, Group2"```

**Comment by ishubin** [comment]
I have just added support for groups in standard test suite and in JavaScript tests

Standard test suite:
```
@@ groups mobile, home, iphone
Home page test
    http://testapp.galenframework.com
         check homepage.spec
```

In JavaScript tests:
```
grouped(["mobile"], function () {
    test("Home page on mobile device", function () {
    });
});
```

**Comment by hypery2k** [comment]
the groups are working:
![galen_reports](https://cloud.githubusercontent.com/assets/979121/6491089/349fcc4c-c2ab-11e4-9103-97608e13efab.png)
But can you add the tag column also on the report?

**Comment by ishubin** [comment]
To be honest I don't like the idea of collecting the used tags from the test report and using it in overview report. First of all the test report is structured and may have multiple layout reports in it. To collect all the data you have to do it recursively. Another problem appears when the test was interrupted with an exception before checking the layout. Then in that case its tags value will be empty. 

With this test groups feature I wanted to have something similar to TestNg Groups. Galen Framework should be very flexible. My original intention was that each test should know to which groups it belongs before the execution. So that you could obtain all of its groups in all event handlers (afterTest, beforeTest, testFilter). As a galen user I can design my test suite with groups in my own way. For instance I can put layout tags together with page name and maybe even a flow name (e.g. "mobile", "loginpage", "authorization", "userflow"). Then in the end I will be able to run only test for specific device, or for specific page or flow. 

I completely understand what you wanted to have in the report but I would like to have a more flexible solution to this problem. For instance when you design your own framework on top of Galen - you could set groups to your tests based on their parameterizations. In the end that information would be gathered in the overview report. So even if the test was interrupted with an exception, you will still be able to see which tags were supposed to be used in it. Let me finish this feature first and I will show you samples. I am almost done

**Comment by hypery2k** [comment]
i can live with the group things. In the end it makes it clearer and the tags remain for spec usage. that's working for my project. ;)

**Comment by ishubin** [comment]
Fixed. The feature is now in release-1.6 branch

**Comment by ishubin** [comment]
In case you have groups specified you can now filter your tests on groups.
Also there are two tabs in html overview report for tests view and groups view

**Comment by hypery2k** [comment]
I've tested the latest version and works great for by basic browser tests from Java so far
