### ISSUE TITLE
Add 'between' spec

### ISSUE THREAD

**Issue by erquhart** [galenframework/galen#123]
It's common to measure the distance between list items. Currently doing so requires this:

```
# test distance between list of 3 items
[1-2]
box-@
  near: box-@{+1} 10px left
```

It would be great to use a syntax similar to the `centered` spec to make this succinct:

```
box-*
  between horizontal: 10px
```

That would tell Galen to test for 10px space between each item's adjacent right and left sides, but it won't check for an item to the left of `box-1` or to the right of `box-3`.

**Comment by ishubin** [comment]
From version 1.6 it is possible to have a custom implementation via "rules" to cover this specific case
