### ISSUE TITLE
Add Mocha js tests to maven

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#142]
Perhaps this article could help http://stackoverflow.com/questions/19829284/is-there-any-mocha-maven-plugin

**Comment by hypery2k** [comment]
see also #181

**Comment by hypery2k** [comment]
the test results are also reported in JUnit, see https://martinreinhardt-online.de/jenkins/view/Galen/job/GalenFramework_build_fork/

**Comment by ishubin** [comment]
Thanks! thats very helpful! I will merge your change later today. Just don't have time at the moment to review it.
Also I see that your job also performs the jslint checks. That is really cool. I am going to improve the js code as well. Will work on it later

**Comment by hypery2k** [comment]
ok, so I will not touch the js code for now.
I will work on the editor ;)
