### ISSUE TITLE
Syntax highlighting for Sublime Text

### ISSUE THREAD

**Issue by erquhart** [galenframework/galen#153]
Just a heads up: we published a basic syntax highlighting plugin for Galen users on Sublime Text. Hoping to add more functionality as we go.

https://github.com/professant/sublime-galen

**Comment by ymarushchenko** [comment]
Can it be converted and used with Notepad++?

**Comment by erquhart** [comment]
I would assume not - Notepad++ plugins appear to be written in C, while Sublime plugins are written in Python. And while compilation may be possible, Sublime plugins use Sublime's api (Textmate's in the case of syntax highlighting).

**Comment by erquhart** [comment]
You could always just, ya know, use Sublime :)

**Comment by danielbayerlein** [comment]
I think you can close this issue because the plugin is incompatible with the current version of Galen, see https://github.com/professant/sublime-galen/issues/1.
