### ISSUE TITLE
Use galen.config as a default config file name

### ISSUE THREAD

**Issue by erquhart** [galenframework/galen#167]
Not sure if this is possible, but this became an issue when I began distributing test files according to our general project testing pattern. Test exists next to the code that it tests (or in Galen's case, next to the layouts). There are times when I need to call a specific page or feature test directly, which will be nested in the page directory, and Galen has no way of finding the config. Current workaround is distributing copies of the config file.

**Comment by ishubin** [comment]
I guess I will just make `galen.config` - a default config file name and use `config` name as a fallback. Just to have  backward compatibility
