### ISSUE TITLE
Add option for object to be omitted in page dump

### ISSUE THREAD

**Issue by erquhart** [galenframework/galen#177]
Technically this could be accomplished by keeping a secondary test file just for page dump, but doing so across many files and keeping those synced with the 'real' test files would be burdensome. Especially when the goal is often to simply omit one or two objects that won't dump.

The use case for me is repeated items that contain off-screen members, such as a carousel. A multiple object locator works fine for the test, but will error out in a dump because it's off screen. I'd like to exclude those selectors for dumping purposes.

**Comment by ishubin** [comment]
One idea that comes to mind - classes or annotations for objects in spec file. This way we could group some objects and later execute page dump only for specific group or excluding a group. Later this functionality of grouping objects could be also used in spec itself for applying validations. Though it makes it all more complicated so I still need to think this through properly
