### ISSUE TITLE
Provide a way to pass data from javascript test file to spec

### ISSUE THREAD

**Issue by erquhart** [galenframework/galen#178]
This would be an augmentation of the `checkLayout` function that would allow an object to be passed as an argument, and then made available within the spec file.

The immediate use case is differences in browsers. There are often 1px differences for various rules, and simply allowing a 1px margin of error isn't an option for some projects. We need to know that things are exactly what is expected. I'd like to pass in the name of the browser so that a spec can change conditionally.

**Comment by jameseisenhauer** [comment]
+1

**Comment by ishubin** [comment]
Missed this story. I guess it is already implemented in the release-2.0 branch. https://github.com/galenframework/galen/issues/274

**Comment by erquhart** [comment]
!!!!! Did not know this was implemented! Youdaman, Ivan.
