### ISSUE TITLE
Test retry handler

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#184]
It would be nice to have a test retry mechanism like in TestNG. This will be applied on the JavaScript tests and in Standard test suite. Requirements still need to be clarified. Could be something like this.

```
testRetry(function (test, retryCount) {
    if (retryCount > 2) {
        return false;
    }
    else return true;
});
```

It should also produce only the reports of the last retry of a test so that we don't get all the original failed reports. And also the retry should kick in only in case the test run was failed

**Comment by ishubin** [comment]
Fix is in release-1.5 branch

**Comment by cpapazaf** [comment]
Hi there,

I was looking how to rerun the tests but using the DSL instead. Is there any recommended way to do that?

Thanks

**Comment by ishubin** [comment]
@cpapazaf What do you mean by `using the DSL instead`?

**Comment by cpapazaf** [comment]
As far as I understand in order to use the snippet above we need to implement our tests in JS. I'm using the Spec API to implement them (http://galenframework.com/docs/reference-galen-spec-language-guide).
