### ISSUE TITLE
Collaboration within community

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#189]
We should discuss how to work together on galen:

* code formatter
* CI job
* more documentation (javadoc)
* directly work on the next dev-release as collaborator instead of forking

Maybe we should arrange a hangout or ....

**Comment by hypery2k** [comment]
I've experimented with [http://docs.travis-ci.com/user/gui-and-headless-browsers/](Travis CI) a little bit, but I think it's easier to set up several jobs within [https://www.cloudbees.com/resources/foss](Dev@Cloud on CloudBees) and using it together with [https://developer.cloudbees.com/bin/view/DEV/Sauce+OnDemand+Service](SauceLabs)

**Comment by ishubin** [comment]
Thanks! I will try to set it up in cloudbees then

**Comment by hypery2k** [comment]
we should definitly try to add some CI server for the project. Would be helping if you register the project on CloudBees and once it's available you can add me as a user. I can then configure the jobs

**Comment by ishubin** [comment]
Yes, I will pick this up as soon as possible
