### ISSUE TITLE
Custom screenshot handler for layout check

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#191]
Galen should be more extendable once it comes to taking screenshot. Users should be able to override the Galen behavior on making screenshot when the it checks layout.

Users should be able to
* Override functionality for taking screenshots in:
    * Java tests
    * JavaScript tests 
    * Standard Test Suite
* Generate layout report without screenshot at all.

**Comment by ishubin** [comment]
I think I know how to implement it without serious refactoring. Just create a function which accepts a screenshot as an argument. This way in checkLayout method it will not make screenshot any more.
```
// in javascript

checkLayout({
    driver: driver,
    path: "homepage.spec",
    screenshot: "screenshot.jpg"
});
```

**Comment by pankaj-anuragi-tft** [comment]
hi, i am trying to take screenshot , but its still giving me screenshot with header and footer , here is my code for the same:

` image = await browser.takeScreenshot();`
i'm using webdriverio+appium (1.15.0)
