### ISSUE TITLE
Improve image cleanup

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#194]
I've found that the screenshots for the reports are also saved in Java tmp directory.
Even after creating of the HTML report they're still preserved. They should be removed after report creation.

It's should be possible to delete temp files when the Java VM exists ...

**Comment by ishubin** [comment]
Why is it important to delete these screenshots from temp files? 
If it is created in the galen code somewhere - then I agree it should do a cleanup afterwards. But if it is generated by the webdriver itself - then I am afraid it might be hard to identify these files

**Comment by hypery2k** [comment]
I'm not sure if it's created by web driver. Just saw this on our build server, I will investigate on this and come back with more details

**Comment by hypery2k** [comment]
The GalenUtils screenshot method uses java temp to create temporary files. The file won't be deleted automatically, from the [JavaDoc](http://docs.oracle.com/javase/7/docs/api/java/io/File.html#createTempFile%28java.lang.String,%20java.lang.String,%20java.io.File%29):

>This method provides only part of a temporary-file facility. To arrange for a file created by this method to be deleted automatically, use the deleteOnExit() method.

Even adding deleteOnExit() doesn't help, as it's not really reliable. I will add a JVM hook and try it locally .

**Comment by hypery2k** [comment]
with the latest changes no temporary files remain in temp dir anymore...

**Comment by hypery2k** [comment]
the fix for the temp file error remains in 1.6.1

**Comment by hypery2k** [comment]
oh I see the error: Within the Java tests normally we don't use GalenMain. Instead we use HtmlReportBuilder directly. So I have to call the cleanup routine directly.

I think within Release 2.0 we should unify the JavaScript and JavaAPI

**Comment by ishubin** [comment]
Ah, so that's what it is :) I completely forgot about your Java-based tests. Yes, we will need to provide better Java docs and also put some more information on the website
