### ISSUE TITLE
Improve detail test results report

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#196]
On the report details view it would be nice to have a switch to show only failed specs:
![galen_report_details](https://cloud.githubusercontent.com/assets/979121/5719831/6b5cee9c-9b1c-11e4-9b52-a80cd790682c.png)

**Comment by ishubin** [comment]
@hypery2k I like the concept. But how about just having an icon button instead of the big button with text? I can imagine at some point the report will have more functions and it might just get a horizontal menu with icons. What do you think about that?

**Comment by hypery2k** [comment]
I've updated the screenshot. Something like that?

**Comment by ishubin** [comment]
Yes, could be. The design of the button itself is not that important. We can later check different concepts. The most important part in this case is actual functionality. I just wanted to note that we should keep in mind that the menu might grow in future

**Comment by ishubin** [comment]
Is this functionality still relevant? Because with the latest html reports you can expand only the error node in the report. I think that is enough.

P.S. I am just going through a list of all issues and trying to clean it.

**Comment by hypery2k** [comment]
no, the improved report is sufficient
