### ISSUE TITLE
Make reporting optional for dumps

### ISSUE THREAD

**Issue by erquhart** [galenframework/galen#202]
We use dumps extensively in testing, and almost never need to reference the generated reports. Manually deleting them is a speed bump that we'd like to get rid of. What do you think about simply utilizing the `--htmlreport` flag for dumps? Without it, the dump would simply generate images, and adding it would produce the full report.

**Comment by ishubin** [comment]
I see your problem. But which way are you using page dumps? Via command line or via JavaScript function? Because if it is the second then I would rather have an extra argument in the function itself.

**Comment by erquhart** [comment]
Ah, you're right, we do use js for dumps, extra argument would be great.
