### ISSUE TITLE
Component spec path is not properly resolved in Windows

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#204]
The original message from user:

When i am running the sample program from the github(https://github.com/galenframework/galen-sample-java-tests/tree/master/src/test) its throwing error meesage as 
FAILED: loginPage_shouldLookGood_onDevice(net.mindengine.galen.java.sample.components.GalenTestBase$TestDevice@21d8d293)
net.mindengine.galen.parser.FileSyntaxException: java.io.FileNotFoundException: Can't find file or resource: \specs\common.spec
in /specs/loginPage.spec:1

**Comment by hypery2k** [comment]
I've updated it to a newer galen version: https://github.com/galenframework/galen-sample-java-tests/pull/1

**Comment by ishubin** [comment]
You think it will fix it? I just don't have a windows machine at all so can't really verify it

**Comment by hypery2k** [comment]
I've tried it on Windows 7 and it works ;)

**Comment by ishubin** [comment]
Thanks for checking it :)
