### ISSUE TITLE
Google group

### ISSUE THREAD

**Issue by claytonneal** [galenframework/galen#209]
Is it possible to create a google user group?
I mean to avoid commenting on your pages with general questions... a group would be searchable too.
Thanks

**Comment by hypery2k** [comment]
You can join the Gitter Chatroom, See readme on github

**Comment by ishubin** [comment]
I think google group might be a good idea. We can use Gitter just for dev and organizational communication. And use Google Group for answering general questions.

**Comment by ishubin** [comment]
Created the group https://groups.google.com/forum/#!forum/galen-framework
