### ISSUE TITLE
New spec suggestion, EqualWidth, EqualHeight

### ISSUE THREAD

**Issue by claytonneal** [galenframework/galen#216]
Hello.
If i have a css like:
myitems-*   css  div.myitems
And i want to check that all divs have the same width and height, could we have a spec like:

myitems-*:
    equalwidht
    equalheight

it will check all items are the same.
This is a more dynamic approach than having to specify px values...

Thanks

**Comment by ishubin** [comment]
I think it should be possible to cover your example with feature #161. Though it is not yet finished.
Once that feature is implemented you will be able to create your own functions (rules).
It will work something like this:
```
| myitems-* should have equal width and height

@@ rule: %{objectPattern} should have equal width and height
    [ ${forEach(objectPattern)} ]
    @
        width: ${findFirst(objectPattern).width()} px
        height: ${findFirst(objectPattern).height()} px
@@ end
```
So something like that. This should give you a basic idea of the custom rules feature
