### ISSUE TITLE
Galen Specs Lang v2

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#217]
After 1.5 years working on Galen its language structure didn't change much. But it was implemented poorly since at that time I didn't know where it all is going to end up. We have added conditional checks, scripts, and now also in a new version we are adding custom rules which will work as a sort of a function. 

I see that the language becomes more and more complex and its getting harder and harder to maintain it and improve. And what is more important - its getting less readable when applied to complex page layouts. We need to build it all over again from scratch. It will be possible to keep the old language for some time to make galen backward compatible.

The new language will be structured based on indentation
I have made a draft of new specs language https://gist.github.com/ishubin/8ea58f3e24c456972a90
Please give me some feedback on it here in comments.

## Acceptance criteria
* Page spec parser implementation
* '%' for warning level in specs
* Page Dump should be updated to new syntax
* Documentation update
   * Galen spec language guide page
   * Tutorial
   * Readme file
* integration tests should be updated to new syntax
* galen-samples-tests needs to be updated

**Comment by hypery2k** [comment]
some suggestions from my side here https://gist.github.com/hypery2k/aa8c018db4c3d343eb12

**Comment by erquhart** [comment]
One thing I do like from @hypery2k 's suggestion is the use of human readable commands over special characters (check "Header" vs - Header -). Using a word like "check" just makes sense, whereas special characters add a bit more to the foreign appearance of the code, and ups the learning curve a bit.

Two things I don't see addressed, and which may be out of scope for a discussion about syntax, is first class citizenship for 1) complex filtering in the tag system and 2) access to data from the calling context. My sense of how crucial these are leads me to expect to see them in a discussion about how the language works, as I believe they would be used extensively in most scenarios, and would significantly reduce the amount of code written in test files.

**Comment by ishubin** [comment]
@erquhart I get it. My main idea was that the language should not just allow to specify a complex layout. But it also should be used as a documentation page. That is why I tried to implement it in a semi-markdown way. As for learning curve I think it will be the same as for learning the special symbols or special keywords. To be honest the first draft I made for myself almost a year ago was completely based on keywords. I didn't like it because when I wrote a big and complex spec - it lost its visual clarity. But since I am the only one with this idea - I will again test different ways. I will put all of them in this story so we can see several options. Actually I think that there might not be a single language. In future anyone will be able to write their own language for Galen. Because in the end the compiled structure is the same. For instance one of the ways I see in future for generating a page spec - Scala with custom DSL or JavaScript.

As for your question on complex filtering with tags. The way it will work will change. From this moment each section will by default match any tag (Like if you specify '*' tag). And only those sections that would have tags specified - those will be applied for a filter. This will help to have a maintainable section structure on a page. I will also provide explanation with concrete examples later. It's just really a lot of work.

As for access to data context - it will not be changed that much. The only thing that will be added is a scope.  That is because in the new language everything will be parsed as a structure. This will allow to use multi-level loops and there will be no variable conflict because of the scope.

**Comment by ishubin** [comment]
I have added another draft of the GalenSpecs language https://gist.github.com/ishubin/8ea58f3e24c456972a90#file-draft-v2-2-spec
This specific draft has couple of changes compared to previous:
* All special keywords are defined via ```@``` symbol. This makes it easer to parse a page spec and also I think it is easer to read the spec
* All checks are started with ```-``` symbol. This also makes it easier for parsing and reading.
* The sections are marked with ```=``` symbol at the beginning and ending of line

I am just playing with different syntax ideas. In the end I will collect the best working ideas into final draft.

**Comment by hypery2k** [comment]
the spec2 seems great, but one minor issue. Can we use
```
"Header"
    @tags( mobile, tablet)
        header :
    @(*)
        footer :
```
instead of
```
= Header = 
    = @( mobile, tablet) =
        header :
    = @(*) =
        footer :
```

what do you mean?

**Comment by ishubin** [comment]
Yeah, I also thought about using double quotes. But then I thought that in this case syntax might be inconsistent as the double-quotes are already used in spec notes http://galenframework.com/docs/reference-galen-spec-language-guide/#Notesforspecs. This could confuse users. I also thought about using triple double-quotes for section names :) but a bit  unsure about it. Because in Scala triple quotes are used for multi-line strings without escape symbols.

As for tags, I think you might have a point there. The reason I wrapped tags in ```@( ... )``` construction, was that I wanted to have an ability to include tags in section definition. So I wanted to mix the section name together with tags. Maybe it is not such a good idea. I will try to see if there is a better way.
