### ISSUE TITLE
Full page screenshot (merging)in chromedriver not working as expected

### ISSUE THREAD

**Issue by phystem** [galenframework/galen#237]
I have tested the http://testapp.galenframework.com/ with different sizes .for size 320x480 there is a problem with attaching the screenshot it seems as it has to scroll down to take it.It's working fine in firefox not in chrome.Attached firefox and chrome screenshots for reference
<br/>
<b>Chrome Wrong screen shot</b>
<br/>
![chrome](https://cloud.githubusercontent.com/assets/11405204/6776374/a5a39d9e-d163-11e4-9d6e-a80184243d27.png)
<br/>
<b>Firefox correct and expected screenshot
<br/>
![firefox](https://cloud.githubusercontent.com/assets/11405204/6776373/a5a2c2f2-d163-11e4-96d7-4991f16c1dbc.png)

**Comment by ishubin** [comment]
Thanks, I am going to investigate this issue.
By the way In which version of galen framework is that?

**Comment by phystem** [comment]
1.5.3

**Comment by phystem** [comment]
I looked into that issue.and found the solution.It is bcoz.When the page is loaded(ie after the login is clicked from the home page)the scroll bar is in middle.So you have to make it to the top then you have start taking and stitching the screenshots..
https://github.com/galenframework/galen/blob/release-1.6/src/main/java/net/mindengine/galen/utils/GalenUtils.java

In the GalenUtils class  -> public static File makeFullScreenshot(WebDriver driver) throws IOException, InterruptedException

if you add scrollVerticallyTo(driver, 0); as first line it is working fine

<br/>Problem <b></b>
![test](https://cloud.githubusercontent.com/assets/11405204/6777956/639a6390-d174-11e4-8810-27e10fc45c4e.png)

**Comment by ishubin** [comment]
I thought I had that. Weird. I will look into the decent code for version 1.6.0 and will release an update.
Thanks!
