### ISSUE TITLE
Group links on tests tab not working

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#238]
The links to the groups are not working on the first tab when using special characters, like spaces:
![galen_reports](https://cloud.githubusercontent.com/assets/979121/6780524/578205ee-d166-11e4-8017-395e484ac09a.png)

Links from group tab are working

**Comment by ishubin** [comment]
Thanks! Will fix it in 1.6.1 version then

**Comment by hypery2k** [comment]
i will push a bugfix, currently testing it ;)

**Comment by ishubin** [comment]
Ok, cool :)
