### ISSUE TITLE
Feature Request: Adding URL-Parameter in Report for sorting

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#240]
Would be very nice to add the ability to add a path parameter to the set the desired sorting:

![galen_reports](https://cloud.githubusercontent.com/assets/979121/6780854/f36ee858-d168-11e4-8030-8b75e1fbe750.png)

So it's easier within a CI environment to send mails to Galen report with sorting by errors ;)

Additionally persistence of the sorting would be nice. So if you selected an detailed report and go back to the overview page you're previous sorting remains. I think we can implement it with the help of the URL parameter.

**Comment by ishubin** [comment]
I think it is a good idea. But I think it is better to have this sorting by failures functionality by default. At the same time it might be a good idea to be able to send a link with sorting for any column, not just failed. This can be done via hash component in url.

**Comment by hypery2k** [comment]
that's 100% my approach ;)

**Comment by ishubin** [comment]
I have already changed the default sorting by failed tests and then by name. I think we can leave the sorting from url functionality as it is not that important. In most cases what we care are failed tests.

**Comment by hypery2k** [comment]
sure, its okay for me
Thanks

**Comment by ishubin** [comment]
I have reopened this issue because it is not yet properly tested.

**Comment by hypery2k** [comment]
I agree.
Is it possible to back port this function to the 1.6 release?

**Comment by ishubin** [comment]
I would rather finish the work with release 2.0 as soon as possible

**Comment by hypery2k** [comment]
ok, I understand that
