### ISSUE TITLE
java.lang.RuntimeException: Specified area is outside for original image

### ISSUE THREAD

**Issue by tarundwivedi** [galenframework/galen#263]
java run time error for Chrome browse
Window 7
![issue_galen](https://cloud.githubusercontent.com/assets/4815705/7111731/98d9763c-e1e0-11e4-8feb-26441aef73b9.png)
Find out issue at Attached screenshot. galen is taken incorrect area for image comparing.
I am using galen API for automation and addition question how to set config property in galen API ?

**Comment by ishubin** [comment]
You are running Galen in Java tests?

**Comment by hypery2k** [comment]
with which version of galen do you get the error? Can you post you're java code?

**Comment by tarundwivedi** [comment]
yes i am using java 

and i am using galen version : 1.5.4

**Comment by hypery2k** [comment]
please enable fullscreen in the config, see my sample project here https://github.com/holisticon/galen_samples

**Comment by tarundwivedi** [comment]
![image](https://cloud.githubusercontent.com/assets/4815705/7112791/e022a1e4-e1ea-11e4-9687-b9679879e837.png)

enable full screen property but still not look good for chrome browser please look in to this 
galen.browser.screenshots.fullPage = true
 
any Suggestion/Query from your side. what is should do

**Comment by ishubin** [comment]
@tarundwivedi when you click on this failing spec in the report does it highlight it properly on the page?
And also is the screenshot stitched properly? Because in Chrome Galen has to scroll the page and stitch all those small screenshots into one large page screenshot.

**Comment by tarundwivedi** [comment]
@ishubin  Yes failing spec is displayed on the page, and screenshot stitched also properly.

now @ishubin  it is working when i have added JavaScript for scroll at top of window for chrome browser before spec file and galendump page also not throw any error for this

**Comment by ishubin** [comment]
@tarundwivedi please try the latest version of Galen Framework 1.6.2. In it we fixed this issue and Galen scrolls to top before making a screenshot

**Comment by ishubin** [comment]
so, what do we do with this issue? Shall we close it?

**Comment by tarundwivedi** [comment]
@ishubin  thanks for Assistance its is really so fast response from your side .. 

yes close it this bug and again thanks
