### ISSUE TITLE
Responsive Testing with REMs

### ISSUE THREAD

**Issue by ianburrett** [galenframework/galen#264]
I recently found the framework and really like it. I can see it has real potential in the automated testing process.

However we use SASS for our CSS and have chosen to use REM's for measurements.

Are there any plans in the pipeline to support REMs as Firefox is the default browser I was hoping it would work, but sadly it errored saying px or % only.

**Comment by ishubin** [comment]
Galen Framework is used for testing the actual layout that is rendered in a browser and not for testing CSS. That is why it checks everything in pixels because that is what in the end you get when you open a website in your browser.

**Comment by ishubin** [comment]
And by the way Galen doesn't even care about CSS properties like "width" and "height" when testing the element "width" and "height" specs. It fetches the actual boundary box in pixels and then applies the validation. That is why every is verified in pixels. Even the percentage based validation is also applied based on pixel values

**Comment by ianburrett** [comment]
Thanks for the rapid and comprehensive response.  Much appreciated!
