### ISSUE TITLE
For mobile resolutions, scrollbar need to be removed when page opens up while execution

### ISSUE THREAD

**Issue by sanjumk** [galenframework/galen#265]
For mobile resolutions, scroll bar on right side of window need to be removed when page opens up while execution. scroll bar consumes almost 17 px of page and so the content of webpage behaves differently when same page is viewed using Ctrl+Shft+M

**Comment by ishubin** [comment]
I don't understand this issue. Why is it so important to remove the scrollbar? How does that make a difference to the page? And what does your Ctrl+Shft+M actually do? For me it does nothing

**Comment by sanjumk** [comment]
It make difference in case of only responsive design, when we have to deal with different resolutions such as- 320x480, 320x568 etc. For example, consider an ecommerce site with responsive design implemented in mobile resolution :-320x480, the search results page is designed to show 2 product images/row. But when page opens up while executing galen spec, with scrollbar on rightside and so entire page content is pushed inside and it is observed that instead of displaying 2 product images per row, only single product image is displayed,whereas by changing resolution in Browser(Ctrl+shft+M-320x480) the page is displayed with 2 product images per row as expected.

**Comment by ishubin** [comment]
Ah, that's what you mean. I get it now. But unfortunately we can't solve this in galen framework as it is specific to the browser and the operating system. What actually happens is that selenium resizes a window of a browser. And then the actual page might take a bit less than that.
You can handle this yourself in your tests. Either create a small framework that would handle this, or just parameterize tests with two version of size: one for reporting and one for actual resizing

**Comment by ishubin** [comment]
Actually, I think we can implement a nice trick for this one. After resizing a browser, we could execute a JavaScript that would take the client area width. We will check the difference between this value and browser window width and by that we will know the exact width of scrollbars and window border. After all this will again change the size of a browser with adjusted width

**Comment by phystem** [comment]
After this I thought the following-this had nothing to to with this issue
1)To hide the scrollbar in chrome while taking full-page screenshots(coz it will make screenshot neat without scrollbars after stitching)..Also this would mean slight pixel difference in calculated one and screenshot one.
2)So hide the scrollbar completely in-case of chrome if full-page screenshots is enabled that will solve the 1)

Is there any problem with what I suggested

**Comment by ishubin** [comment]
How would you hide the scrollbars? This is a thing that is specific to browser and this functionality is not provided by Selenium. And I don't want to mess with all these browser specific settings in Galen Framework as its going to be a headache in maintenance. 
As I understood the problem which @sanjumk described is that they want to test that at specific resolution - they get a mobile layout. But if they provide that resolution as it is - then the resulting page size will be smaller by few pixels because of scrollbars. So in the end they get incorrect layout.

**Comment by phystem** [comment]
I got what you are saying .
But a simple javascript injection will hide the scrollbar this has nothing to do with selenium
`document.body.style.overflow = 'hidden'`

**Comment by ishubin** [comment]
@phystem That will hide the rest of the page, why would we do that?

**Comment by hypery2k** [comment]
this would just hide the scrollbar, I like the idea of this approach. If we want to remove the scrollbar width we have to distinguish for browser and operating system, e.g. on OS X the scrollbar is much much thinner ...

**Comment by ishubin** [comment]
if you run the javascript ```document.body.style.overflow = 'hidden'``` - you will not be able to take the complete screenshot of the page. You will only get the viewport area. I just tried it on a large page and it basically hides the page.
Also I would like not to mess with browser specific things in Galen Framework. If we start adding support for that - then it will become a headache in maintenance when new versions of browsers are released. Lets keep it simple. As I said above we can solve the original problem of the issue by increasing the size of browser to adjust its client side area

**Comment by phystem** [comment]
I got the idea from 'Full Page Screen Capture' a chrome extension which takes screenshot of whole page without scrollbar

Full Page Screen Capture
![image](https://cloud.githubusercontent.com/assets/11405204/7199737/c0a87ece-e514-11e4-8e7a-174787cde67e.png)

Generated Image
![image](https://cloud.githubusercontent.com/assets/11405204/7199796/1a8f120e-e515-11e4-8923-75e716ed337c.png)
  
Zoomed to 100% image
![image](https://cloud.githubusercontent.com/assets/11405204/7199806/353c4ac2-e515-11e4-898e-ba6590ede5a3.png)

**Comment by ishubin** [comment]
Seems like the support for auto adjusting the browser width is already in 2.0.
Here is the property that enables this feature https://github.com/galenframework/galen/blob/master/galen-core/src/main/java/com/galenframework/config/GalenProperty.java#L54

**Comment by tillsc** [comment]
Isn't this the same issue as #3 ?

**Comment by ishubin** [comment]
@tillsc I am not sure, to be honest. As far as I remember I posted issue #3 because I had issues with viewport in Internet Explorer 8 browser. But I am not sure if it is still relevant because I didn't really use "viewport" object in my galen tests

**Comment by tillsc** [comment]
AFAICS you're using `window.innerWidth` in [`GalenUtils.getViewportArea()`](https://github.com/galenframework/galen/blob/86ac75ba3807dcbecedb3cae59a966306c6dd815/galen-core/src/main/java/com/galenframework/utils/GalenUtils.java#L447). But this [includes vertical scrollbars](https://developer.mozilla.org/de/docs/Web/API/window/innerWidth) (while the fallback `document.documentElement.clientWidth` doesn't). 

Am I getting something wrong or is this a bug?

**Comment by ishubin** [comment]
@tillsc This could be a bug. Let me check that one later

**Comment by ishubin** [comment]
@tillsc Sorry for such late reply. You are right. I guess I will just switch these statements around.

**Comment by tillsc** [comment]
I'm using a workaround in the meantime: https://gist.github.com/tillsc/90e975a0b95ae18d3242

**Comment by matze09** [comment]
It seems the fix from October 5th is already in the 2.1.3 release. Can you confirm this?
I just checked and the issue still remains.

I'm testing a responsive view with a media-breakpoint at 980 px. Due to the scrollbars, the desktop-view only becomes visible at something larger than 980px, but should be at _exactly_ 980 px.
This issue only occurs in Chrome.

```
@@parameterized
| deviceName | tags | size | browser |
| 980x1024 | desktop | 980x1024 | chrome |
```

**Comment by matze09** [comment]
@tillsc Thanks for the workaround. How exactly does this JS-snippet have to be used? 
Sorry, I'm quite new to this...

**Comment by tillsc** [comment]
@matze09 You can use this workaround only for [JavaScript based tests](http://galenframework.com/docs/reference-javascript-tests-guide/)

**Comment by matze09** [comment]
Ah, okay! Thanks for pointing me to that section of the docs... :)
