### ISSUE TITLE
How to resolve the issue- OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by sanjumk** [galenframework/galen#266]
How to resolve the issue- OutOfMemoryError: Java heap space. The Error report is attached here.
![oomerror](https://cloud.githubusercontent.com/assets/11961341/7175203/9010b726-e42f-11e4-8fff-572bc7423dc5.jpg)

**Comment by ishubin** [comment]
Could you please put the complete stacktrace in text instead of image?

**Comment by ishubin** [comment]
I can already see that something is wrong when saving an image via rainbow4j. Will try to fix it in version 2.0. What is the approximate size of the page? Maybe it is too big.
