### ISSUE TITLE
Unable to target css pseudo selectors in spec syntax

### ISSUE THREAD

**Issue by jeanpaulgorman** [galenframework/galen#270]
When setting up a css or xpath spec selector e.g. .form-base__radio:before the tests don't run and the spec fails.

I'm running Galen Framework on OSX

**Comment by ishubin** [comment]
Unfortunately there is no way to handle this situation as Selenium doesn't support pseudo selectors

**Comment by jeanpaulgorman** [comment]
Thanks for the update :)
