### ISSUE TITLE
Shorthand color notation doesn't work

### ISSUE THREAD

**Issue by DaanDD** [galenframework/galen#281]
When using this notation:

```
panelPrimary
  color scheme: > 10% #fff
```

I get this output:

```
    panelPrimary
->      color scheme: > 70% #064b8d, > 10% #fff
->      :   color #000fff on "panelPrimary" is 0% but it should be greater than 10%
```

`#fff` is being converted to `#000fff`, so it seems like shorthand notation for colors is not supported at the moment.

**Comment by ishubin** [comment]
Thanks for reporting this. Will pick it up.
