### ISSUE TITLE
multiple click in single .js

### ISSUE THREAD

**Issue by nishantkumar155** [galenframework/galen#287]
this.LoginPage = function (driver) {
  GalenPages.extendPage(this, driver, {
    
    browsebycat: "xpath: //A[contains(@href, '#browsebycat')]", // xpath locator
    newestapi: "xpath: //A[contains(@href, '#newestapi')]", // xpath locator
    

    load: function () {
      this.open("mysite");
      return this.waitForIt();
    },
    
     hoverAs1: function () {
       this.browsebycat.click();
      
    },

    hoverAs2: function () {
       this.newestapi.click();
      
    },

  });
};
var loginPage = new LoginPage(driver).load();
loginPage.hoverAs1();

loginPage.hoverAs2();

**Comment by ishubin** [comment]
What is that?
