### ISSUE TITLE
Missing WebDriver Param not throwing error when trying to run Chrome

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#289]
If I run galen tests without the Webdriver param from command line and try to use Chrome all tests are executed without runtime errors:
```
galen test cssPage.test -DwebsiteUrl=http://getbootstrap.com --htmlreport ../../reports/bootstrap/home

```
see here my  cssPage.test:

```
@@ table browsers
    | browerName | browser |
    | Chrome     | chrome  |
    | Firefox    | firefox |
@@ table devices
    | deviceName | tags      | size     |
    | Mobile     | mobile    | 320x600  |
    | Tablet     | tablet    | 640x480  |
    | Desktop    | desktop   | 1024x800 |
@@ parameterized using browsers
@@ parameterized using devices
@@ groups css
css page on ${deviceName} in ${browerName} browser
  selenium ${browser} ${websiteUrl} ${size}
    check specs/cssPageLayout.spec --include "${tags}"
```
I would suggest throwing an error if I enforce chrome and the driver env property is not set

**Comment by ishubin** [comment]
I don't get it. Are you telling that you really use chrome, and it really open chrome window and performs testing in it and you don't even give it a system property for chromedriver?

**Comment by hypery2k** [comment]
With the chromedriver property Galen just run's my test in the three devices in firefox without any complains ;)

**Comment by ishubin** [comment]
But then what is exactly wrong with that? Why would you take it as a bug?

**Comment by hypery2k** [comment]
I show you next week during the hangout ;)
