### ISSUE TITLE
FR: make this/self available in a component

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#294]
When creating a component spec, I cannot find a way to test properties of the main element (the one selected in the spec that then refers to the component spec). As we have "parent", I would expecting to also have something like a "self" or "this" locator in this context.

**Comment by ishubin** [comment]
You can use "parent" for that as it references the component main element. But to make it more clear in the spec files we can add a second name like "self"

**Comment by hypery2k** [comment]
You're right, "self" would be more readable ...
