### ISSUE TITLE
Heatmap in html report

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#295]
It would be nice to have an overview of what is checked on the page for particular layout check in the HTML report

**Comment by hypery2k** [comment]
would be a great feature. Maybe it's possible to use transparent overlays for that. So you would get some kind of a heat map how much a feature is checked...

**Comment by ishubin** [comment]
Yeah, I am working on this already. I like the idea of heat maps. will try out different concepts

**Comment by ishubin** [comment]
So far here is what I have achieved:
<img width="743" alt="screen shot 2015-08-06 at 4 02 38 pm" src="https://cloud.githubusercontent.com/assets/949577/9113402/ae881596-3c54-11e5-9fb9-48f48deb64dc.png">
<img width="568" alt="screen shot 2015-08-06 at 4 02 50 pm" src="https://cloud.githubusercontent.com/assets/949577/9113403/ae8a815a-3c54-11e5-91e0-d16d4d9aff36.png">

Maybe will tune colors a little bit

**Comment by hypery2k** [comment]
that's really cool
