### ISSUE TITLE
Sharing the HTML reports via Mail / Messenger cannot be viewed the receiver

### ISSUE THREAD

**Issue by sachinkodagali** [galenframework/galen#331]
Hi,

Currently we are facing a issue with sharing HTML reports ..

We run the galen tests and get the HTML reports in local. We attach these reports on mail / messenger. When the receiver downloads them they aren'
![pasted image at 2015_10_16 06_24 pm](https://cloud.githubusercontent.com/assets/5982311/10628578/82b8ae6e-77e4-11e5-898b-89745a2b0828.png)
t able to access the reports

Attached is the image that the receiver sees .. All the links here are not clickable and user isnt able to navigate through the HTML report ..

**Comment by ishubin** [comment]
@sachinkodagali Do you send the complete folder with css and js in it or just the html files?

**Comment by sachinkodagali** [comment]
We send the HTML files directly

**Comment by ishubin** [comment]
That will not work as html reports are quite big. They have css, js files and also screenshot png files in the report folder. You need to send all of that. What you could do is upload them to some hosting and then just share a link to the reports. In my company our galen html reports are hosted automatically in Jenkins CI and we just share a link to these reports

Closing as this is not an issue of galen

**Comment by sachinkodagali** [comment]
Thanks. One question :

If we run a test twice HTML report is overwritten .. is there a way to name these reports in command line, as uploading them everytime is difficult and we may lose on Reports as we end up doing multiple executions ..

**Comment by sachinkodagali** [comment]
One more thing :

We tried to upload a file on a free hosting website (E.g. filedropper.com, google drive etc). After upload, we downloaded the file and we still get the same PNG file that we had attached when the bug was logged.

Can you please respond ASAP on the same as we need to share our reports to everyone in the team ..

**Comment by hypery2k** [comment]
depends on how you use galen. If you are using the command line (http://galenframework.com/docs/reference-working-in-command-line/#Singlepagetest) you can something like this:

```
galen check homepage.gspec
    --url "http://example.com"
    --size "640x480"
    --javascript "some.js"
    --include "mobile,all"
    --exclude "toexclude"
    --htmlreport "htmlreport-dir/$(date +"%Y%m%d%H%M")"
    --testngreport "report/testng.xml"
    --jsonreport "jsonreport-dir"
```

**Comment by ishubin** [comment]
@sachinkodagali 
I already explained how the Galen HTML reports are generated. What you are dealing with is not a Galen issue at all. Please do not use the "ASAP" abbreviation for such matter. Because this is simply rude to demand someone to fix your own problem for you ASAP. I am going through lots of user queries lately and I am trying to be helpful and assist people. So as Martin. But this is now going too far. I am stepping in ASAP only when it is a serious issue and the core functionality is crashing. What you asked - is a matter of configuring a web hosting. Please, first try to google an answer for that, or ask your developer colleagues.

**Comment by sachinkodagali** [comment]
Thanks @hypery2k .. We will use the date format in the command line .. However when we use galen test (with a js file) is there a way to do the same?

**Comment by sachinkodagali** [comment]
@ishubin - We really appreciate your help on our queries, When i said ASAP it meant that can you check and hint on the steps you have already followed, didnt mean that i was rude. Sure i will go ahead on google and resolve this now ..
