### ISSUE TITLE
Providing Switches in Chrome Driver

### ISSUE THREAD

**Issue by Purus** [galenframework/galen#333]
My application works only in Chrome when we disasble the security in the browser. 

The below code is what we use generally in Java to create a driver with custom options to add flags.

What would be the equivalent in galen for JavaScript API?

~~~
ChromeOptions options = new ChromeOptions();
options.addArguments("--disable-web-security");
WebDriver driver = new ChromeDriver(options);
~~~

**Comment by Purus** [comment]
I could not find any solution related to Galen JavaScript API on this.

Any thoughts?

**Comment by ishubin** [comment]
Closing it as this is not an issue of Galen

**Comment by Purus** [comment]
For documentation purpose:

https://groups.google.com/forum/#!topic/galen-framework/zNxtZ8BSCZQ

Actually that code should work exactly the same in JavaScript API. The only thing you need to do - import Java classes before you use them. Galen uses Mozilla Rhino JavaScript interpreter. Here is an example of how to import Java class http://www-archive.mozilla.org/rhino/apidocs/org/mozilla/javascript/ImporterTopLevel.html

**Comment by hypery2k** [comment]
you can create a custom driver, see http://galenframework.com/docs/reference-javascript-tests-guide/#Creatingdriver

But please use the Google Group for this kind of questions: https://groups.google.com/forum/#!forum/galen-framework

**Comment by Purus** [comment]
Hi @hypery2k 

I have created a post in the group. Please refer https://groups.google.com/forum/#!topic/galen-framework/zNxtZ8BSCZQ.

The docs link does not explain about Switches, which is different than Capabilities in my understanding. That's where I am unable to proceed.
