### ISSUE TITLE
Commandline inject error

### ISSUE THREAD

**Issue by akshayashet** [galenframework/galen#334]
Issue:  getting following error : 
![image](https://cloud.githubusercontent.com/assets/3539011/10727389/786e2d2a-7bff-11e5-9a6f-01ba78fcb648.png)

Test File : 
![image](https://cloud.githubusercontent.com/assets/3539011/10727405/9cb82b5e-7bff-11e5-983b-522125611b01.png)

If i remove ```inject testRemove.js``` then its working absolutely fine.
Please help me to solve this issue.

**Comment by hypery2k** [comment]
which version of galen are you using?

**Comment by akshayashet** [comment]
I am using v2.1.2

![image](https://cloud.githubusercontent.com/assets/3539011/10751144/6ec28c40-7ca3-11e5-9288-e6a0bbd8a338.png)

**Comment by ishubin** [comment]
@akshayashet It says that you have inconsistent indentation on line 13. So that means that the amount of spaces in the line 12 and line 13 do not match, or you might have a mix of tabs and spaces which is not consistent. Could please check that?

**Comment by akshayashet** [comment]
@ishubin Right!!!. It was indentation issue. Converted all tabs to space. Working fine now. Thanks a lot.
