### ISSUE TITLE
Relative path in TestSuites not resolved

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#344]
If you're using test suite and the paths to the Spec files are relative the paths are not resolved, see the following folder structure:
```
project-dir
  test
    layout
      specs
        home.spec
      homepage.test
```

If I run Galen from the project with `galen test homepage.test` dir I get the following error:
```
check specs/home.gspec --include "mobile,phone,XS"
java.io.FileNotFoundException: specs/home.gspec
	at com.galenframework.speclang2.reader.pagespec.PageSpecReader.read(PageSpecReader.java:46)
```

homepage.test:
```
@@ table browsers
    | browerName | browser |
    | Chrome     | chrome  |
@@ table devices
    | deviceName    | tags                      | size      |
    | XS            | mobile,phone,XS           | 320x600   |
    | S             | mobile,phone,S            | 500x800   |
    | M             | mobile,tablet,M           | 780x1080  |
    | L             | desktop,L                 | 1024x800  |
    | XL            | desktop,XL                | 1280x1024 |

@@ parameterized using browsers
@@ parameterized using devices
@@ groups homepage
homepage on ${deviceName} in ${browerName} browser
  selenium ${browser} ${websiteUrl} ${size}
    check specs/home.gspec --include "${tags}"
```

I think adding relative file read [here](https://github.com/galenframework/galen/blob/master/galen-core/src/main/java/com/galenframework/utils/GalenUtils.java#L363) with a '.' could solve this issue-

**Comment by ishubin** [comment]
Not sure about that. While inside specs it does make sense to do that, and it is already implemented like that and works. But for test, I would say it is the same as in Java project you have tests located in various levels (packages) but they all refer to files starting from working directory. I think implementing this feature will make it more confusing.
For instance in other test projects Galen tests are spread in different folders and the specs are all managed in a separate folder. If every test would start searching for a spec within its own folder - that would make a mess there
