### ISSUE TITLE
Allow section filtering by name when checking layout

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#350]
It would be nice to test only a specific section of spec by providing simple section regex

- [x]  Implement section filtering in SectionValidation
- [x]  Add support for section filter in test suites (GalenPageActionCheck)
- [x]  Add support for section filter in JS api
- [x]  Add section filter in command line `check` command

**Comment by vickywu2017** [comment]
Hi, I think Galen is a great tool to check the web page layout. But I am wondering how to execute a test for checking a special section not all sections in the gspec file, I don't want to split the gspec file to many gspec files. Is there any solution about this? Thank you very much!

**Comment by t2hv33** [comment]
I have the same issue as @vickywu2017 
How to Allow section-filtering by name when checking layout.

**Comment by ishubin** [comment]
That is what this issue is about. I haven't started yet working on it but soon will

**Comment by ishubin** [comment]
Implemented in `release-2.4` branch
