### ISSUE TITLE
Add a support for custom test name in TestNG and JUnit tests

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#362]
Comes from https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/galen-framework/OMJu2kBpKzY/vOx6pgLlBgAJ

**Comment by hypery2k** [comment]
we can already overrated the testname

**Comment by ishubin** [comment]
@hypery2k This is the place where it takes the name https://github.com/galenframework/galen/blob/master/galen-java-support/src/main/java/com/galenframework/testng/GalenTestNgTestBase.java#L37
You mean just override that method?

**Comment by hypery2k** [comment]
yes something like this. In the Junit TestBase there's an dedicated methods for that https://github.com/galenframework/galen/blob/master/galen-java-support/src/main/java/com/galenframework/junit/GalenJUnitTestBase.java#L39

**Comment by ishubin** [comment]
@hypery2k By the way I really don't like that the test name is taken by creating a fake exception and reading the stacktrace signatures. Isn't there a better way of getting a test name in JUnit?

**Comment by stefanbirkner** [comment]
#364 does not create a fake exception anymore. I have a deeper look into Galen's JUnit integration for improving the test name stuff.
