### ISSUE TITLE
Unable to see my test cases failing

### ISSUE THREAD

**Issue by makkar-nishant123** [galenframework/galen#376]
I am using followiing for testing but unable to see my testcases failing in case of Negative scenerios :

	public void checkLayout(Config testConfig, String specPath,String tagname)
	{   int  totalError=0;
		List<String> tag=new ArrayList<String>();
		if(resultsDir == null) resultsDir = testConfig.getRunTimeProperty("ResultsDir") + "/galen-html-reports";
		if(tagname.equalsIgnoreCase("firefox")) tag.add("firefox");
		else if(tagname.equalsIgnoreCase("chrome")) tag.add("chrome");
		else if(tagname.equalsIgnoreCase("ie")) tag.add("ie");
		else{
			tag.add(tagname.toLowerCase());
		}
		//Setting config value true for screen shot.
		GalenConfig.getConfig().setProperty(GalenConfig.SCREENSHOT_FULLPAGE, "true");
		
		String title = "Check layout " + specPath;
		LayoutReport layoutReport = null;
		try
		{
			layoutReport = Galen.checkLayout(testConfig.driver, specPath, tag, null, new Properties(), null);
		}
		catch (IOException e)
		{
			testConfig.logException(e);
		}
		
		report.get().layout(layoutReport, title);
		
		if (layoutReport.errors() > 0)
		{  totalError =layoutReport.errors();
			testConfig.logFail("Incorrect layout: " + title);
			
			List<ValidationResult> validationResult = layoutReport.getValidationErrorResults();
			for (int i = 0; i < validationResult.size(); i++)
			{
				//Logging Error message
				Log.FailWithoutPageInfoLogging("ERROR:" + validationResult.get(i).getError().getMessages().get(0), testConfig);
			}
			testConfig.logFail("TOTAL FAILED SPEC :"+totalError);
		}

**Comment by ishubin** [comment]
Please post your question on https://groups.google.com/forum/#!forum/galen-framework google group. We can discuss this problem there and if it appears to be an issue of galen framework we will post it on github
