### ISSUE TITLE
Reporting // Warnings on HTML Report and Heatmap

### ISSUE THREAD

**Issue by larsreith** [galenframework/galen#379]
Hi,

for improved handling and working with warnings, I suggest to
- mark warnings yellow on heat map instead of red
- mark warnings yellow on report html instead of red

**Comment by ishubin** [comment]
Hi,

I am not sure what you mean in this case. The purpose of heatmap is to check how often an element was checked on the page. The more red you see - the better coverage you have. It basically just counts the number of times the element was mentioned in actual specs.  I don't see how a warning level could have a different effect on this calculation

As for yellow warnings in report html - I thought they are already reported as yellow (or orange). If that is not the case then I think we are talking about a bug here :) Could you please attach the reports so I can see if there is something wrong with warning level?

**Comment by larsreith** [comment]
Hi,

- for warnings on the heat map see my comment on #380.
- for warnings on the report.html, see the screenshots. (In particular, the component should be marked as warning and not as error if it contains no errors but only warnings)

![warnings-in-subcomponents](https://cloud.githubusercontent.com/assets/1035293/12553949/6ae34f88-c37a-11e5-9023-ef09acedc2b1.jpg)

**Comment by ishubin** [comment]
@larsreith will fix the warnings in components in version 2.3
Thanks!
