### ISSUE TITLE
Comments in .test files

### ISSUE THREAD

**Issue by kanadakid** [galenframework/galen#383]
Hi,

I'm wondering if there is a way to comment out lines in a Galen .test file? I looked at the reference page for Galen Test Suite Syntax, but I didn't find anything relevant there. We have some large test files and commenting out lines is easier than removing them if we are trying to isolate a problem.

Thanks!

**Comment by ishubin** [comment]
That should work the same way is in specs. Use the leading `#` symbol:

```
Home page test
    http://example.com
        check some.gspec

# the following code is commented out
#Another home page test
#    http://example.com
#        check anothersome.gspec
```

Also you can disable tests temperorarily http://galenframework.com/docs/reference-galen-test-suite-syntax/#DisablingTests
