### ISSUE TITLE
Cant build with maven-frontend-plugin.version 0.0.20

### ISSUE THREAD

**Issue by cyildirim** [galenframework/galen#392]
I cloned repository and i tried build it with mvn. And i got this error
`Execution install node and npm of goal com.github.eirslett:frontend-maven-plugin:0.0.20:install-node-and-npm failed
`

when i switch to `maven-frontend-plugin.version` to `0.0.23` i works well. 

Is it common problem or specific for me ?

**Comment by hypery2k** [comment]
the 0.0.20 version is used for older maven version, see https://github.com/eirslett/frontend-maven-plugin/issues/319 So It's a maven error. You can install an older maven aside and source another maven home for this repo ;)

**Comment by cyildirim** [comment]
Problem solved. @hypery2k Thanks for comment
