### ISSUE TITLE
Html reporter should also give overview of all failed specs

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#4]
At the moment once you get a big report file with around 1000 checks - it is hard to scroll to failed checks. There should be a way to aggregate all failed specs with error messages in one place (perhaps in the beginning of a report we could put a "Failed" section )

**Comment by hypery2k** [comment]
seems to be obsolete with #145 or?

**Comment by ishubin** [comment]
@hypery2k I dont' know. What do you thinks is the current html report functionality enough? This issue was introduce for cases when you have a big page spec with hundreds of checks. I haven't tested yet this new report on a real big project so I don't know if it is really effective enough.

**Comment by hypery2k** [comment]
of course, you're right. But now we have groups for sorting and we can sort by failed tests. So i think it's enough for handling huge scenarios ...

**Comment by ishubin** [comment]
Yeah, agree. Lets leave it for now and see what kind of problems appear next time
