### ISSUE TITLE
Error: Could not start galen

### ISSUE THREAD

**Issue by arkroy** [galenframework/galen#410]
Hi 

I'm trying to use the galenframework with gulp through the NPM modules, however I'm getting the following error. Please could you help.

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Could not start galen. Galen ('/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/galenframework/bin/galen') not found?
    at ChildProcess.<anonymous> (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galen/lib/gulp-galen.js:104:30)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
Arks-MacBook-Air:fti_corp ark$

**Comment by hypery2k** [comment]
You already opened several issues see https://github.com/hypery2k/galenframework-cli/issues/26 and https://github.com/hypery2k/gulp-galenframework/issues/7

I suggest already to support you. So please don't raise further issues

**Comment by arkroy** [comment]
Sorry didn't notice, you were the author for all of those modules as well. Apologies. 
I'll wait for your response.

PS: I've installed galenframework and galenframework-cli both globally and locally yet I'm now getting the following error:

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Could not start galen. Galen (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galenframework/lib/../node_modules/galenframework/bin/galen.cmd) not found?
