### ISSUE TITLE
Unable to check text using UTF-8 spec file

### ISSUE THREAD

**Issue by APshenkin** [galenframework/galen#412]
Hi!

Founded issue with cyrilic texts validadion.

It's work only, if spec file has ANSI encoding (windows 1251)

If I create the spec file using UTF-8, then when I try to validate cyrilic text I get this error:
```"headerContainer.headerRight.linkVK" text is "Наш паблик ВКонтакте" but should be "Р?Р°С? РїР°Р?Р?РёРє Р?Р?Р?Р?С?Р°РєС?Р?"```

Looks like Galen think, that spec file should be in ANSI and get wrong text.

Also I tried to use this parameter in command line `-Dfile.encoding=UTF-8` but it didn't work.
Reproduced on Windows 8.1 (russian localization)
Is there any way to use UTF-8 encode for galen on Win?

Thanks in advance!

**Comment by ishubin** [comment]
Ok, seems like this old issue is back :) I guess we have to do something about it. Thanks for reporting!

**Comment by APshenkin** [comment]
Hi!
Just fixed this issue.
Here is PR https://github.com/galenframework/galen/pull/422

**Comment by ishubin** [comment]
@APshenkin thanks! I left a comment to your fix. By the way have you tested this fix on your own project?

**Comment by APshenkin** [comment]
@ishubin Yes, I tested a fix and it works great with Arabic and Cyrillic characters

**Comment by ishubin** [comment]
@APshenkin thanks!
