### ISSUE TITLE
issue for firefox loading the domain on latest version (w7)

### ISSUE THREAD

**Issue by eparisio** [galenframework/galen#413]
Hi, i have a problem with the last version of firefox (43.0.1) for windows (7).

when the tests (gspecs) runs it opens correctly the firfox window but it stop on the initial "learn more" preloaded standard tab whitout loading the domain and after a while it go in error (probably a timeout error plus an internal error).

I tested on chrome and IE and the tests/browsers works fine.

there the test:

    ${page_name} on ${deviceName} device
      selenium firefox http://${domain}:9001 ${size}
        wait 5s until visible "id: newsletter-modal"
          check specs/hpPB.gspec --include "${tags}"

i have tested it even on non local domains and the error is the same.

there the error log (sorry if seems to long but they are 2 error and the space there is smaller than screen):

> org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
445372927390webdriver-profile\\extensions\\fxdriver@googlecode.com","installDate":1460388235068,"updateDate":1460388235068,"applyBackgroundUpdates":1,"bootstrap":false,"size":8234871,"sourceURI":null,"releaseNotesURI":null,"softDi
sabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms
":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1460388235466   addons.xpi      DEBUG   Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"YM7Fz5HSHF8t","location":"app-global","version":"43.0.1","type":"theme","internalName":"classic/1.0","updateU
RL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributo
rs":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate"
:1458655497776,"updateDate":1458655497776,"applyBackgroundUpdates":1,"skinnable":true,"size":24172,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibilit
y":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"43.0.1","maxVersion":"43.0.1"}],"targetPlatforms":[]}
1460388235466   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1460388235466   DeferredSave.extensions.json    DEBUG   Save changes
1460388235466   addons.xpi      DEBUG   Updating database with changes to installed add-ons
1460388235466   addons.xpi-utils        DEBUG   Updating add-on states
1460388235467   addons.xpi-utils        DEBUG   Writing add-ons list
1460388235473   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1460388235473   addons.manager  DEBUG   Provider finished startup: XPIProvider
1460388235473   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1460388235473   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1460388235473   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1460388235474   addons.manager  DEBUG   Starting provider: GMPProvider
1460388235477   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1460388235477   addons.manager  DEBUG   Provider finished startup: GMPProvider
1460388235477   addons.manager  DEBUG   Starting provider: PluginProvider
1460388235477   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1460388235477   addons.manager  DEBUG   Provider finished startup: PluginProvider
1460388235478   addons.manager  DEBUG   Completed startup sequence
1460388235678   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1460388235678   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1460388235678   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1460388235732   DeferredSave.extensions.json    DEBUG   Starting write
1460388235929   addons.repository       DEBUG   No addons.json found.
1460388235929   DeferredSave.addons.json        DEBUG   Save changes
1460388235930   DeferredSave.addons.json        DEBUG   Starting timer
1460388235940   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1460388235940   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1460388235940   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1460388235947   DeferredSave.extensions.json    DEBUG   Write succeeded
1460388235947   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
1460388235993   DeferredSave.addons.json        DEBUG   Starting write
1460388236106   DeferredSave.addons.json        DEBUG   Write succeeded

 >       at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:122)
        at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:276)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:221)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:133)
        at com.galenframework.browser.SeleniumBrowserFactory.getDriver(SeleniumBrowserFactory.java:95)
        at com.galenframework.browser.SeleniumBrowserFactory.createLocalBrowser(SeleniumBrowserFactory.java:89)
        at com.galenframework.browser.SeleniumBrowserFactory.openBrowser(SeleniumBrowserFactory.java:65)
        at com.galenframework.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:73)
        at com.galenframework.tests.GalenBasicTest.execute(GalenBasicTest.java:55)
        at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
        at com.galenframework.TestRunnable.run(TestRunnable.java:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows:
445372927390webdriver-profile\\extensions\\fxdriver@googlecode.com","installDate":1460388235068,"updateDate":1460388235068,"applyBackgroundUpdates":1,"bootstrap":false,"size":8234871,"sourceURI":null,"releaseNotesURI":null,"softDi
sabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms
":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1460388235466   addons.xpi      DEBUG   Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"YM7Fz5HSHF8t","location":"app-global","version":"43.0.1","type":"theme","internalName":"classic/1.0","updateU
RL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributo
rs":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate"
:1458655497776,"updateDate":1458655497776,"applyBackgroundUpdates":1,"skinnable":true,"size":24172,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibilit
y":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"43.0.1","maxVersion":"43.0.1"}],"targetPlatforms":[]}
1460388235466   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1460388235466   DeferredSave.extensions.json    DEBUG   Save changes
1460388235466   addons.xpi      DEBUG   Updating database with changes to installed add-ons
1460388235466   addons.xpi-utils        DEBUG   Updating add-on states
1460388235467   addons.xpi-utils        DEBUG   Writing add-ons list
1460388235473   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1460388235473   addons.manager  DEBUG   Provider finished startup: XPIProvider
1460388235473   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1460388235473   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1460388235473   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1460388235474   addons.manager  DEBUG   Starting provider: GMPProvider
1460388235477   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1460388235477   addons.manager  DEBUG   Provider finished startup: GMPProvider
1460388235477   addons.manager  DEBUG   Starting provider: PluginProvider
1460388235477   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1460388235477   addons.manager  DEBUG   Provider finished startup: PluginProvider
1460388235478   addons.manager  DEBUG   Completed startup sequence
1460388235678   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1460388235678   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1460388235678   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1460388235732   DeferredSave.extensions.json    DEBUG   Starting write
1460388235929   addons.repository       DEBUG   No addons.json found.
1460388235929   DeferredSave.addons.json        DEBUG   Save changes
1460388235930   DeferredSave.addons.json        DEBUG   Starting timer
1460388235940   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1460388235940   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1460388235940   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1460388235947   DeferredSave.extensions.json    DEBUG   Write succeeded
1460388235947   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
1460388235993   DeferredSave.addons.json        DEBUG   Starting write
1460388236106   DeferredSave.addons.json        DEBUG   Write succeeded
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'ITEM-67686', ip: '172.30.194.199', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_77'
Driver info: driver.version: FirefoxDriver
>        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:134)
        at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:276)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:221)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:133)
        at com.galenframework.browser.SeleniumBrowserFactory.getDriver(SeleniumBrowserFactory.java:95)
        at com.galenframework.browser.SeleniumBrowserFactory.createLocalBrowser(SeleniumBrowserFactory.java:89)
        at com.galenframework.browser.SeleniumBrowserFactory.openBrowser(SeleniumBrowserFactory.java:65)
        at com.galenframework.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:73)
        at com.galenframework.tests.GalenBasicTest.execute(GalenBasicTest.java:55)
        at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
        at com.galenframework.TestRunnable.run(TestRunnable.java:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
445372927390webdriver-profile\\extensions\\fxdriver@googlecode.com","installDate":1460388235068,"updateDate":1460388235068,"applyBackgroundUpdates":1,"bootstrap":false,"size":8234871,"sourceURI":null,"releaseNotesURI":null,"softDi
sabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms
":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1460388235466   addons.xpi      DEBUG   Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"YM7Fz5HSHF8t","location":"app-global","version":"43.0.1","type":"theme","internalName":"classic/1.0","updateU
RL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributo
rs":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate"
:1458655497776,"updateDate":1458655497776,"applyBackgroundUpdates":1,"skinnable":true,"size":24172,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibilit
y":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"43.0.1","maxVersion":"43.0.1"}],"targetPlatforms":[]}
1460388235466   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1460388235466   DeferredSave.extensions.json    DEBUG   Save changes
1460388235466   addons.xpi      DEBUG   Updating database with changes to installed add-ons
1460388235466   addons.xpi-utils        DEBUG   Updating add-on states
1460388235467   addons.xpi-utils        DEBUG   Writing add-ons list
1460388235473   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1460388235473   addons.manager  DEBUG   Provider finished startup: XPIProvider
1460388235473   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1460388235473   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1460388235473   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1460388235474   addons.manager  DEBUG   Starting provider: GMPProvider
1460388235477   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1460388235477   addons.manager  DEBUG   Provider finished startup: GMPProvider
1460388235477   addons.manager  DEBUG   Starting provider: PluginProvider
1460388235477   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1460388235477   addons.manager  DEBUG   Provider finished startup: PluginProvider
1460388235478   addons.manager  DEBUG   Completed startup sequence
1460388235678   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1460388235678   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1460388235678   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1460388235732   DeferredSave.extensions.json    DEBUG   Starting write
1460388235929   addons.repository       DEBUG   No addons.json found.
1460388235929   DeferredSave.addons.json        DEBUG   Save changes
1460388235930   DeferredSave.addons.json        DEBUG   Starting timer
1460388235940   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1460388235940   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1460388235940   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1460388235947   DeferredSave.extensions.json    DEBUG   Write succeeded
1460388235947   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
1460388235993   DeferredSave.addons.json        DEBUG   Starting write
1460388236106   DeferredSave.addons.json        DEBUG   Write succeeded
 >       at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:122)

**Comment by ishubin** [comment]
@eparisio Which galen version are you using?

**Comment by eparisio** [comment]
2.1.0 sorry.
i will try to update the version and see if the error persists.

**Comment by eparisio** [comment]
Hi, i have try to update the version from node (npm install -g galenframework-cli,npm update -g galenframework-cli) but i don't know why it continue to use the 2.1.0 version.

i have try removing it and reinstalling but the result is the same, i download a version before 2.2 because i don't have support for @groups declarations

**Comment by hypery2k** [comment]
did you recently updated you're node version?

**Comment by eparisio** [comment]
Ok i have resolved it, upgraded from node and works fine.
but now i need a way to change the default proxy setting on new selenium firefox instance to use no proxy.
