### ISSUE TITLE
Path replace in JsFunctionLoad not working correctly in windows

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#414]
If I use [custom rules](http://galenframework.com/docs/reference-galen-spec-language-guide/#CustomRules) on Windows the path is not correctly replaced:

![windows_load_script_error](https://cloud.githubusercontent.com/assets/979121/14461461/fcb516a0-00c2-11e6-8b4a-01dfb09e860d.png)

The error is this line in [JsFunctionLoad.java]( https://github.com/galenframework/galen/blob/226a5d25e77495b21a67e23ff21e92dc5544b7b2/galen-core/src/main/java/com/galenframework/javascript/JsFunctionLoad.java#L75)

You'll find the example code here: https://github.com/hypery2k/galen_samples/tree/master/testng

The error only occurs on Windows

**Comment by ishubin** [comment]
I thought I already got rid of this stupid `./` thingy. Thanks for notifying, will take a look at it

**Comment by adamjson** [comment]
@hypery2k I was able to workaround this locally by commenting out a few lines in JsFunctionLoad. It may help you in the short term: https://github.com/galenframework/galen/issues/318

**Comment by ishubin** [comment]
I am closing this issue, as we already had and issue posted for it. Lets track it in #318
