### ISSUE TITLE
Allow nested selectors 

### ISSUE THREAD

**Issue by svenhornberg** [galenframework/galen#417]
Please allow nested selectors like [nested objects](http://galenframework.com/docs/reference-galen-spec-language-guide/#Objectdefinition).

old:
```
search_panel:
search_panel.input:
search_panel.button:
```
new:
```
search_panel:
    input:
    button:
```

**Comment by ishubin** [comment]
What is this issue about? Could you please explain what do you mean by allowing nested selectors? How is that different from what is already mentioned in the documentation?

**Comment by svenhornberg** [comment]
maybe I am missing something, but this isnt possible for me:

```
@objects
    search_panel   #search-bar
        input      input[type='text']
        button     a

@on *
		search_panel:
			visible
                    input:
                                vissible
```

I have to write :


```
@objects
    search_panel   #search-bar
        input      input[type='text']
        button     a

@on *
		search_panel:
			visible
                search_pane.input:
                        vissible
```

basically it would be nice to omit search_panel for nested selectors. Like in [yaml](https://en.wikipedia.org/wiki/YAML). I want to intent a sub-selector and omit the base selector.

**Comment by ishubin** [comment]
Ah, now I see which part you are talking about :)
To be honest I don't see a benefit in such solution. It is completely non-readable for me. If you want to optimize your test code I would suggest to either use object matchers like this:

```
    search_panel*:
        visible
```

Or do it explicitly like this:

```
    search_panel, search_panel.input, search_panel.button:
        visible
```

Or do it using object groups

```
@objects
    search_panel   #search-bar
        input      input[type='text']
        button     a
@groups
    all_search_elements     search_panel, search_panel.*

= Testing search =
    &all_search_elements:
        visible
```

**Comment by svenhornberg** [comment]
Thanks for the help this is a lot better, but I have to say the visible check was a very simplified example to make my point. If I want to check each element for an specific size or position, I can not group my objects like this and a prefix operator like "-" would save some code.

But I understand your point :) . Maybe others share my opinion and it will be reopened again.
