### ISSUE TITLE
Using fullPage with --size

### ISSUE THREAD

**Issue by OleVik** [galenframework/galen#425]
I run parameterized tests for testing specific device widths, and in the working directory I have set `galen.browser.screenshots.fullPage = true` in `galen.config`. However, the resulting screenshots are cut off at the set size. How can I have fixed widths but variable heights to capture the full page?

Here is the test, `cross-browser.test`, that I run:

```
@@ Set
    domain  example.com
    gridUrl http://192.168.99.100:4444/wd/hub

@@ parameterized
    | browser            | browserName        |
    | firefox            | Firefox            |
    | chrome             | Chrome             |
@@ parameterized
    | deviceName | tags      | size     |
    | Mobile     | mobile    | 320x600  |
    | Tablet     | tablet    | 640x480  |
    | Desktop    | desktop   | 1024x800 |

Front on ${deviceName} in ${browserName}
    selenium grid ${gridUrl} --browser "${browser}" --page "http://${domain}" --size ${size}
        dumps/${deviceName}-${browserName}-Front_${size}
```

**Comment by ishubin** [comment]
Hi @OleVik 
Do I understand it correctly that full page screenshot setting works only horizontally and not vertically? Or it doesn't work at all and galen doesn't scroll the page vertically to assemble all screenshots?

**Comment by OleVik** [comment]
It seems to not work at all, in the sense that the page does fit to the width of the viewport at any size, but the page seemingly is not scrolled to create the higher screenshot. `example.com` may be a poor example (as it's height is very short), but with for example `bbc.com` running the test above I will get screenshots sized 320x600, 640x480, and 1024x800.

I don't quite understand how I can constrain the width but not the height - so I get screenshots where only the width is 320, 640, and 1024, but the height is set to `auto`, ie. it stretches to however long the content is. Are there any sample tests/specs for doing fullpage screenshots with constrained widths? It is really useful for automating/simplifying responsive layout testing.

**Comment by ishubin** [comment]
@OleVik are you using chrome? 

I will try to test it locally in `galen-sample-tests` project and will update it with proper config later today

**Comment by OleVik** [comment]
Both Chrome and Firefox, running in Selenium Grid as nodes (per the `cross-browser.test` above).

**Comment by ishubin** [comment]
@OleVik I don't know what's going wrong on your side but for me it works perfectly. I have prepared a small gist without selenium grid https://gist.github.com/ishubin/be7c8322e08df0ec7949a97e8dd19dc7
I did generate all page dumps with complete full page screenshots

**Comment by mmirold** [comment]
Not sure how Galen's screenshot creation is realized. Depending on the implementation of scroll & stitch, some websites are hard to capture. For instance, when the page's html and body elements are set to 100% height and page scrolling is effectively performed in an inner wrapper div, javascript scrollTo does not work as intended.

**Comment by OleVik** [comment]
@ishubin Apart from a few fixes to run that gist in grid, it worked marvelously. I wonder if my `galen.config` might have been too simple, all I had set was:

```
galen.range.approximation = 5
galen.browser.screenshots.fullPage = true
```

@mmirold I imagine this will become an issue down the line, as one of the pages I intend to test does indeed have scrolling on an inner element. Can the scrollTo be set to target a different element than `body`? I also imagine a fixed header will pose an issue in stitching, but that can be solved by injecting some JS before the screenshot is taken.

**Comment by ishubin** [comment]
@OleVik Strange. Your config is also supposed to work. As for scrolling the inner div - there is no solution for this at the moment in galen. Maybe will figure out something later
