### ISSUE TITLE
Imported locators are not overridden

### ISSUE THREAD

**Issue by lippea** [galenframework/galen#426]
I have one form, which is the same in functionality, but in different place.
So I was thinking reuse the specs but just change the locators.

```
spec1:
@objects
    name css xxx1
@on global
   name:
       visible
spec2:
@import spec1.gspec
@objects
    name css xxx2
```
I would expect when I check the layout with spec2, it will check name is visible with locator from spec2,
But actually it still uses locator from spec1. So I have to duplicate the @on global part in spec2 and keep maintaining to be the same.

**Comment by ishubin** [comment]
If you have a duplicated component in a different place on your website, then I would suggest you to use `component` spec that basically works as a sub-spec http://galenframework.com/docs/reference-galen-spec-language-guide/#Component
