### ISSUE TITLE
Amazon AWS not able to run Galen gspec files

### ISSUE THREAD

**Issue by sukhvinderh** [galenframework/galen#435]
I am trying to run Galen tests on Amazon AWS which are packaged in a Maven project.  Unfortunately, every time I run the tests, AWS is unable to fine gspec file and throws a FileNotFound Exception.  Changed the location of the file from the previous folder to the root folder but in vain.

However, when I extract the .zip project file uploaded to AWS, it clearly has the intended gspec file in the package.

Per my understanding AWS also uses physical devices to run the tests.  Also, these test run fine on any local devices but do not run on AWS Device Farm

**Comment by ishubin** [comment]
Not a Galen issue
