### ISSUE TITLE
image validation is not accurate

### ISSUE THREAD

**Issue by zhangmeng712** [galenframework/galen#437]
I'm using the method of image comparison 
my js is like 
var Url = 'http://mo.m.taobao.com/etao/jusave/h5/branch/meizhuang';

testOnAllDevices('activity Image comparison page', Url, function (driver, device) {
  checkLayout(driver, "specs/comparison.spec", device.tags);
})
my speck is like belows:

@objects
          list_item_first   css  .timeline
=  image compare =
          @on *
              list_item_first:
                  image file ../imgs/list.png, error 4%

however is not locate the right element in ios simulator and sumsung edge device

**Comment by ishubin** [comment]
Could you please provide screenshots and html reports?

**Comment by zhangmeng712** [comment]
![image](https://cloud.githubusercontent.com/assets/1312529/18251740/75b9ee32-73bd-11e6-9512-01c471015275.png)

**Comment by zhangmeng712** [comment]
I found this only happened in safari ios iphone6 9.1 simulator, even I changed the config to galen.browser.pageElement.areaFinder=jsbased_native it was still not correct

**Comment by zhangmeng712** [comment]
I thought that maybe the problem of navigationbar problem 
![image](https://cloud.githubusercontent.com/assets/1312529/18260990/9aeda622-7425-11e6-919f-282e4bc675c8.png)

**Comment by tadesushilgithub** [comment]
How are you doing it for mobile devices?

**Comment by ishubin** [comment]
@zhangmeng712 Yes, you are right that is related to the safari header and at the moment I don't have a solution for this problem

**Comment by sujith0980** [comment]
I am running the test cases on chrome browser and in the reports galen is not highlighting the correct element. Any solution for that?
