### ISSUE TITLE
How does Galen take a screenshot of a DOM element when it doesn't fit the viewport

### ISSUE THREAD

**Issue by kaqqao** [galenframework/galen#449]
Galen is somehow successfully taking screenshots of single DOM elements even when the given element can not fit the viewport.
I sadly can't use Galen the intended way due to messy classloading issues and the fact we use a customized WebDriver (!), so I'm forced to approach the problem sideways.
What I'm trying to achieve is take a screenshot of a single DOM element and compare it with a different image. I'm calling Rainbow4j directly to do this, and it works fine. But if the element is bigger than the viewport, I need to somehow perform the same magic Galen normally does.

**Comment by kaqqao** [comment]
I think I figured it out. One can use `GalenUtils.makeFullScreenshot` to make a full-page screenshot and then crop the BufferefImage by the element dimensions. I presume this what Galen is doing as well.

**Comment by ishubin** [comment]
Yes, that's the right place. As you can see Galen just scrolls page and makes screenshot part by part. And at the end it stitches all of those part together
