### ISSUE TITLE
Chrome test Heat Map image is not showing the page element for out of view page content

### ISSUE THREAD

**Issue by nikolmarku** [galenframework/galen#450]
Hi,

I am running galen test on 3 browsers: FF, IE and Chrome
Chrome : Version 51.0.2704.4 dev-m (64-bit)
Selenium : 52

Galen Framework : Version: 2.3.1
JavaScript executor: Rhino 1.7 release 5 2015 01 29

When I check the test report heat maps they show the full page including the out of view/window page elements on FF and IE browser but not in Chrome. Only the first section [the visible window view] is show and the rest of the page that user need to scroll to view is not sow on heat map.

Regards
Niko

**Comment by nikolmarku** [comment]
![chromedoesnotshowoutofview](https://cloud.githubusercontent.com/assets/8082150/19930880/4abbc24c-a102-11e6-89c4-d9d5c8f46a46.png)
![ff-showcontent](https://cloud.githubusercontent.com/assets/8082150/19930963/a6c24778-a102-11e6-9dc7-a5ce80ac54cd.png)

**Comment by ishubin** [comment]
Hi Niko! Did you try to run the tests with full page screenshot set to true in your config? e.g.

```
galen.browser.screenshots.fullPage = true
```

**Comment by nikolmarku** [comment]
Thanks ishubin, 
is working

Brgs
Niko
