### ISSUE TITLE
Parallel Tests with jUnit

### ISSUE THREAD

**Issue by chrishelgert** [galenframework/galen#451]
Hi,
we are trying to run our galen-tests parallel with jUnit and the maven-surefire-plugin. (parallel=methods, threadCount=4, same with forkCount=4 und reuseForks=true)
currently following error occurrs:
```bash
[ERROR] org.apache.maven.surefire.testset.TestSetFailedException: java.lang.RuntimeException: java.lang.NullPointerException; nested exception is java.lang.RuntimeException: java.lang.NullPointerException
[ERROR] java.lang.RuntimeException: java.lang.NullPointerException
[ERROR] at com.galenframework.junit.JUnitStepListener.testRunFinished(JUnitStepListener.java:51)
[ERROR] at org.junit.runner.notification.RunNotifier$2.notifyListener(RunNotifier.java:95)
[ERROR] at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:61)
[ERROR] at org.junit.runner.notification.RunNotifier.fireTestRunFinished(RunNotifier.java:92)
[ERROR] at org.junit.runner.JUnitCore.run(JUnitCore.java:161)
[ERROR] at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
[ERROR] at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:141)
[ERROR] at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:114)
[ERROR] at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:86)
[ERROR] at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:134)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] Caused by: java.lang.NullPointerException
[ERROR] at java.util.LinkedList$ListItr.next(LinkedList.java:893)
[ERROR] at com.galenframework.reports.json.JsonReportBuilder.createReportOverview(JsonReportBuilder.java:70)
[ERROR] at com.galenframework.reports.HtmlReportBuilder.build(HtmlReportBuilder.java:44)
[ERROR] at com.galenframework.junit.JUnitStepListener.testRunFinished(JUnitStepListener.java:48)
```

i also tried to setup the project from base with [galen_samples](https://github.com/hypery2k/galen_samples) - but after adding our Testcases it also fails.

maybe you know a solution, or does it currently not work?
cli-usage with node have a param "--parallel-tests 8" - maybe there is also parallel-tests for java and i haven´t found it?

**Update:**
found the difference, i´ve updated to the actual galen version, in the galen_samples is 2.2.4 - in this version it works, in the current not :(

**Comment by ishubin** [comment]
@chrishelgert Thanks for reporting! That looks wrong. I don't think it should generate html report with every test. Report generation should be done at the end so I guess that JUnitListener is just totally wrong. I am going to remove it and release a fix once I am done with other stuff. The only problem is that I have already updated selenium to the latest version and that means that for firefox you will have to use geckodriver once galen 2.3.2 is released.

**Comment by ishubin** [comment]
@hypery2k looks like that code is yours. I don't have much experience with junit, could you please take a look at it? From what I can tell generation of reports is in the wrong place. It looks like it executes it every time after each test https://github.com/galenframework/galen/blob/master/galen-java-support/src/main/java/com/galenframework/junit/JUnitStepListener.java#L48

**Comment by hypery2k** [comment]
I will take a look at it tomorrow

**Comment by hypery2k** [comment]
After investigating this a little bit, I don't really get why it's executed each time, because the docs are telling:
```
    /**
     * Called when all tests have finished. This may be called on an
     * arbitrary thread.
     *
     * @param result the summary of the test run, including all the tests that failed
     */
```

**Comment by ishubin** [comment]
@hypery2k sorry, my fault! Looked in the wrong place http://junit.sourceforge.net/javadoc/org/junit/runner/notification/RunListener.html#testFinished(org.junit.runner.Description).

Then the original error is something else

**Comment by hypery2k** [comment]
@chrishelgert Can you show us a simple snippet of your test? Are you extending the GalenJUnitTestBase?

**Comment by chrishelgert** [comment]
@hypery2k we are using https://github.com/hypery2k/galen_samples as base for our galen-tests.
we only modified the test-devices and added some helper-methods for our test-cases. So yes wer are extending the GalenJUnitTestBase.

when i start with your example it works (generate the reports multiple times, but works) - when i upgrade to the latest galen-version the error above occurs.

**Comment by hypery2k** [comment]
okay, I will try with my local setup to resolve this issue, but currently having issues with firefox and selenium. But keep you updated here

**Comment by hypery2k** [comment]
can you try with maven-surefire-plugin.version 2.18.1?

**Comment by chrishelgert** [comment]
I will try it tomorrow :)

**Comment by hypery2k** [comment]
Okay, if this is not working try using my master fork

**Comment by chrishelgert** [comment]
@hypery2k i tried both, but it looks still like the same error

````
ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-cli) on project osecom-layout: Execution default-cli of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: There was an error in the forked process
[ERROR] org.apache.maven.surefire.testset.TestSetFailedException: java.lang.RuntimeException: java.lang.NullPointerException
[ERROR] at org.apache.maven.surefire.common.junit4.JUnit4RunListener.rethrowAnyTestMechanismFailures(JUnit4RunListener.java:213)
[ERROR] at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:109)
[ERROR] at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
[ERROR] at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
[ERROR] at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] Caused by: java.lang.RuntimeException: java.lang.NullPointerException
[ERROR] at com.galenframework.junit.JUnitStepListener.testRunFinished(JUnitStepListener.java:51)
[ERROR] at org.junit.runner.notification.SynchronizedRunListener.testRunFinished(SynchronizedRunListener.java:42)
[ERROR] at org.junit.runner.notification.RunNotifier$2.notifyListener(RunNotifier.java:103)
[ERROR] at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
[ERROR] at org.junit.runner.notification.RunNotifier.fireTestRunFinished(RunNotifier.java:100)
[ERROR] at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
[ERROR] at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[ERROR] at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
[ERROR] ... 6 more
[ERROR] Caused by: java.lang.NullPointerException
[ERROR] at java.util.LinkedList$ListItr.next(LinkedList.java:893)
[ERROR] at com.galenframework.reports.json.JsonReportBuilder.createReportOverview(JsonReportBuilder.java:70)
[ERROR] at com.galenframework.reports.HtmlReportBuilder.build(HtmlReportBuilder.java:44)
[ERROR] at com.galenframework.junit.JUnitStepListener.testRunFinished(JUnitStepListener.java:48)
[ERROR] ... 13 more
```

**Comment by hypery2k** [comment]
mmh strange, cannot reproduce your error locally

**Comment by chrishelgert** [comment]
@hypery2k i´ve  send it on your public email-address

**Comment by hypery2k** [comment]
I've got it and check

**Comment by hypery2k** [comment]
So with the latest master with my second PR (which Ivan already accepted) it's working for me on macOS 10.12 and Win10 without any NPE.

**Comment by chrishelgert** [comment]
@hypery2k great work - i will test it again with the next release 👍

**Comment by ishubin** [comment]
Any news on this issue? Does it still occur?

**Comment by chrishelgert** [comment]
@ishubin sorry was last week in holidays, will try it tomorrow

**Comment by chrishelgert** [comment]
@ishubin, @hypery2k 
nice it works - thank you both :)

i think you can close the issue :)

**Comment by hypery2k** [comment]
you're welcome
