### ISSUE TITLE
-D option in command line doesn't replace config property

### ISSUE THREAD

**Issue by jdariva** [galenframework/galen#455]
When I execute a galen test from the command line (within a Jenkins shell script):

> galen test tests/subhome.test --htmlreport reports --junitreport "junit-report.xml" -Dgalen.browserFactory.selenium.grid.browser=firefox

the execution use the default value I've configure in the config file:

> galen.range.approximation=3
galen.browser.screenshots.fullPage = false
galen.browser.screenshots.fullPage.scrollTimeout = 50
galen.browser.screenshots.fullPage.scrollWait = 20
spec.colorscheme.precision = 256
spec.colorscheme.testrange = 6
galen.browserFactory.selenium.runInGrid = true
galen.browserFactory.selenium.grid.url = http://localhost:4444/wd/hub
galen.browserFactory.selenium.grid.browser = chrome
galen.browserFactory.selenium.grid.platform = LINUX
galen.use.fail.exit.code = true
galen.spec.image.tolerance = 30
galen.spec.image.error = 0px
galen.spec.global.visibility = true
galen.test.file.ext = .test
galen.test.js.file.ext = .test.js

**Comment by cyildirim** [comment]
Can you try comment out  `galen.browserFactory.selenium.grid.browser` line from galen.config ?

**Comment by jdariva** [comment]
Hi. Yes, it works if I comment out that line. 

Thanks!!

**Comment by cyildirim** [comment]
if your problem resolved. Could you close the issue please?  @jdariva
