### ISSUE TITLE
No image related to test, apart of above the fold

### ISSUE THREAD

**Issue by trignolo** [galenframework/galen#464]
I'm trying to execute test on a web page with galen and local browser (I've used Firefox and Chrome). The execution of the test (with **check** command) is correct, but when I check the report I can't see image other than the above the fold web page.
Here an example of what I'm saying:

![layout-1-screenshot](https://cloud.githubusercontent.com/assets/1587396/21806752/7808b8f8-d73b-11e6-84f4-dc90ec347b96.png)

This is the screenshot takes by Galenand I cannot have information of a large portion of the page.

Thanks in advance.

**Comment by ishubin** [comment]
Hi! Is your complain related only to the fact that it took a screenshot of viewport? Or are you complaining about the fact that there is some popup overlay on your website?
If it is the first then you need to define the screenshot behaviour in your galen config like this line https://gist.github.com/ishubin/be7c8322e08df0ec7949a97e8dd19dc7#file-galen-config-L45

By default it is disabled as it is time consuming.

**Comment by trignolo** [comment]
Thanks a lot, it works now with the configuration explicitly enabled.
