### ISSUE TITLE
Typo in docs?

### ISSUE THREAD

**Issue by aleksygoroszko** [galenframework/galen#469]
Galen Specs Language Guide document contains section "Object groups" where you can read: 

> In case you want to assign multiple elements to multiple groups, you can declare groups with square brackets (. For example lets add another group mainframe that will have same elements as in skeleton_elements group but with extra one

It looks like the brackets example does not correspond to sentence about "square brackets".

**Comment by ishubin** [comment]
You are right! Thanks! Funny typo :)
