### ISSUE TITLE
GalenPageDump doesn't clean data

### ISSUE THREAD

**Issue by kalumpiwarra** [galenframework/galen#470]
GalenPageDump does not clean data (screenshot of page) after dump.
For example: Screenshots are not cleared from the directory %TEMP% [Windows].

    public void exportAllScreenshots(PageDump pageDump, Browser browser, File reportFolder) throws IOException {

        File screenshotOriginalFile = browser.getPage().getScreenshotFile();

        FileUtils.copyFile(screenshotOriginalFile, new File(reportFolder.getAbsolutePath() + File.separator + "page.png"));

        BufferedImage image = Rainbow4J.loadImage(screenshotOriginalFile.getAbsolutePath());

        File objectsFolder = new File(reportFolder.getAbsolutePath() + File.separator + "objects");
        objectsFolder.mkdirs();

        for (PageDump.Element element : pageDump.getItems().values()) {
            if (element.getHasImage()) {
                int[] area = element.getArea();

                if (area[0] < image.getWidth() && area[1] < image.getHeight()) {
                    int x = Math.max(area[0], 0);
                    int y = Math.max(area[1], 0);

                    int x2 = Math.min(area[0] + area[2], image.getWidth());
                    int y2 = Math.min(area[1] + area[3], image.getHeight());

                    int availableWidth = x2 - x;
                    int availableHeight = y2 - y;

                    try {
                        if (availableWidth > 0 && availableHeight > 0) {
                            BufferedImage subImage = image.getSubimage(x, y, availableWidth, availableHeight);
                            Rainbow4J.saveImage(subImage, new File(objectsFolder.getAbsolutePath() + File.separator + element.getObjectName() + ".png"));
                        } else {
                            element.setHasImage(false);
                        }
                    }
                    catch (Exception ex) {
                        LOG.error("Got error during saving image", ex);
                    }
                }
            }
        }
    }

Sometimes this situation leads to a considerable reduction of disk space. 
Could you look at the problem?

**Comment by ishubin** [comment]
Thanks for notifying! I will try to fix it in next release

**Comment by ishubin** [comment]
Fixed in `release-2.4` branch
