### ISSUE TITLE
How to cast RemoteWebDriver to AndroidDriver ?

### ISSUE THREAD

**Issue by ajayv1** [galenframework/galen#473]
I am using saucelabs to run test on Mobile devices. In one test, on click of paypal button new window opened but when i log window handles there is only one. Test is not recognising that.

I have already tried solution like "allowPopups = true" and others to solve the issue but not able to make it.
At last, i reached to this solution that AndroidDriver has "contexts()" method which will solve my issue.
How can we cast "RemoteWebDriver" to "AndroidDriver" in Galen?

**Comment by ishubin** [comment]
Looks like this is not an issue of galen framework
