### ISSUE TITLE
Embed galen-extras as a standard library

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#474]
It should be possible to use galen-extras (https://github.com/galenframework/galen-extras) right away as a library, without manually copying it from github repo:

```
@import galen-extras

# ...
```

**Comment by cyildirim** [comment]
Is it possible way ? 
1.  clone galen-extras repo to resources directory with makeDist.sh
2.  implement `ImportProcessor` for galen-extras.

**Comment by ishubin** [comment]
I wouldn't do the first part like that. I think we can just copy all the scripts into gale-core resources and maintain them there. This would also mean that galen-extras repo would become deprecated.

As for `ImportProcessor` we already have something similar. We would just need to extend it so that it allows to import both gspecs and js scripts from galen-core resources.
