### ISSUE TITLE
Can not run galen framework

### ISSUE THREAD

**Issue by matrioska00** [galenframework/galen#478]
Hi everyone!
I'm a new member, I am trying run a fist galen project but it can not run.
It's only run geckodriver and open firefox browser, can not fill link to firefox. I don't know why.
Please help!
Note: I run by cmd on Windows.
![untitled](https://cloud.githubusercontent.com/assets/26320935/23786318/e36aa566-059e-11e7-9412-dcda76ec97e5.png)

**Comment by ishubin** [comment]
Hi. Please move your question to Galen Framework forum (https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/galen-framework)
Also please don't post screenshots of your terminal. Instead format the issue in text. Also provide all the details of your system and browsers (os, galen, java, firefox, chrome)

**Comment by matrioska00** [comment]
Sr, thanks to guide
