### ISSUE TITLE
Getting MissingLocator exception when using xpath in spec/gspec file Java + TestNG + Galenframework

### ISSUE THREAD

**Issue by susnigdha1** [galenframework/galen#486]
Hi,

I am encountering "MissingLocator" exception when using xpath for object declaration in spec/gspec files. I am using TestNG, JAVA and GalenFramework (2.3.2). Given below snapshot:

![image](https://cloud.githubusercontent.com/assets/23377331/25902690/467ef65e-3568-11e7-92d1-e37190412ae0.png)

Regards,
Susnigdha Chatterjee

**Comment by ishubin** [comment]
Your spec is incorrect. You are missing a section definition. For more info see this http://galenframework.com/docs/reference-galen-spec-language-guide/#TaggingandSections
