### ISSUE TITLE
Defining @@groups through parametrized tables

### ISSUE THREAD

**Issue by jackmac92** [galenframework/galen#495]
I would like to be able to define a table e.g.
```
@@ table devices
    | device  | deviceSize              |
    | desktop | ${desktopDimension}     |
    | mobile  | ${mobileDimension}      |

```
which is then used to define the tests @@groups
```
@@ parameterized using devices
@@ groups ${device}
Public ${pageName} on ${device}
```

however this results in the test being part of the "${device}" group, am I doing something wrong, is there another way to define groups through parameterization?

**Comment by cytec** [comment]
i know it's been over a year since the initial issue started but i've got the same thing lately. Any way to get this to work?

I have 8 Devices and 3 Browsers set up to test again and would love to be able to group them by browser/device!

**Comment by ishubin** [comment]
Hi @cytec ! Unfortunately I am not able to pick this up. I decided to stop improving galen test suites syntax, as I want to proceed improving the galen core functionality.
