### ISSUE TITLE
Support full page screenshots

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#50]
For the moment not all browser support full page screenshots. For many browsers Selenium makes screenshot for visible area only. In order to support screenshots for a complete page Galen should scroll the page multiple times and create screenshots of all parts of a page. After that Galen should assembly those parts in a single image

**Comment by tamilselvanps** [comment]
Hai Bro @ishubin still we have faced the chrome screenshot issue.But we cant identified the exact reason why the problem exist in chrome alone.Could you help us to resolve it.
