### ISSUE TITLE
Spec Generator

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#501]
There should be a way to generate galen specs from page dump.

**Comment by arora94surbhi** [comment]
new GalenPageDump(testDevice.getPreviewLink()).dumpPage(driver, "/specs/cinematic/cinematic.gspec" , SPECS_DUMP_PATH);
//spec file need to contain the objects on page for you need to dump specs, and it generates galen specs for all objects specified on the fly in SPECS_DUMP_PATH

**Comment by cyildirim** [comment]
What do you think about putting a plus button near to rules which are listed bottom of the page?  @ishubin I did some basic sketch about how it could be designed


<img width="1680" alt="fullscreen_3_3_18__8_03_pm" src="https://user-images.githubusercontent.com/1422426/36937640-1a4a8fb6-1f1f-11e8-90ae-096d9595c2a8.png">

**Comment by ishubin** [comment]
@cyildirim I like your idea. But the problem with the page dump is that it is quite stupid and gives very inconvenient specs. That is why I didn't spend much time on it and plan to focus more on the java based spec generator.

**Comment by drundanibel** [comment]
@ishubin: Has there been any progress on this Java-based spec generator in the meantime? From my point of view this would be an absolute killer feature to apply Galen to a whole list of URLs in a really automated way, i.e. (almost) without manual effort. Do I have a correct idea of what this feature is supposed to do?  When will it be available?

**Comment by ishubin** [comment]
@drundanibel It is implemented for quite some time already but it is only merged into release-2.4 branch. I have just recently finished working on all the planned features for release 2.4 and currently doing testing and finalising documentation. I hope to make a release very soon.
As for spec generator - yes, I wanted to achieve a reliable way of generating complete specs without any manual effort. Although you are still required to come up with names and locators. But I hope maybe in future we will be able to cover even this part.

**Comment by drundanibel** [comment]
Great, then I'll take a closer look at the release-2.4 branch, thanks for your great work!
