### ISSUE TITLE
forEach:: no check if node exist in spec. No errors in output. Looks as if test pass

### ISSUE THREAD

**Issue by ksiv** [galenframework/galen#523]
@forEach [ some.mistype.here.anywhere* ] as itemName, next as nextItem
            ${itemName}:
                aligned vertically left ${nextItem}
                above ${nextItem} 30 px

**Comment by cyildirim** [comment]
You can add if statement before `foreach` it is not hitting to foreach since `some.mistype.here.anywhere` has not any element.

**Comment by ishubin** [comment]
Galen Specs don't have  a strict check on for loop statemens. Effectively, for loop statement is just a a simple regex that matches any objects declared in the spec. So if it doesn't match anything - it will simply not do anything

**Comment by ksiv** [comment]
Well I m not about any srtict check but warning like "0 element processed", but it might be too good for me or I just misinterpreted the way it should be used :-) Thank you for your quick replies.
