### ISSUE TITLE
Ecmascript 6 syntax not working with Galen

### ISSUE THREAD

**Issue by cyberSane** [galenframework/galen#533]
I tried to use ECMAScript 6 syntax with js helper files which I execute in .test file but it throws syntax error as stated below: 
```
org.mozilla.javascript.EvaluatorException: missing ; after for-loop initializer (jsfiles/click.js#1)
```

## **cat output of jsfiles/click.js**
```
let elementClass = '.toggle';
driver.findElement(By.cssSelector(elementClass)).click();
```

**Comment by hypery2k** [comment]
see #542

**Comment by cyberSane** [comment]
Thanks @hypery2k 
Appreciate the good work!
