### ISSUE TITLE
Chrome Driver not working with Chrome62

### ISSUE THREAD

**Issue by ashwinpreet** [galenframework/galen#537]
When I installed the Galen framework through the npm it install's the chrome driver version 2.31 which is not compatible with the latest chrome version. I have manually deleted the chromedriver from node_modules and updated the latest 2.33 version.
@ishubin Update the scripts to download the latest chrome driver.

**Comment by hypery2k** [comment]
the npm package is not part of this module here, already an issue in my [repo](https://github.com/hypery2k/galenframework-cli/issues/48)

you can try `galenframework-cli@2.3.5-develop-55`

**Comment by ashwinpreet** [comment]
Thanks for the update. I will close this ticket.
