### ISSUE TITLE
Issue in integrating Galen with selenium page object 

### ISSUE THREAD

**Issue by JeffGaly** [galenframework/galen#547]
My project has a selenium with Junit where i want to integrate my galen code to page object by calling spec file .

**Comment by JeffGaly** [comment]
New issue

**Comment by hypery2k** [comment]
Take a look at my [sample repo](https://github.com/hypery2k/galen_samples/blob/master/junit/src/test/java/sample/layout/CssLayoutTest.java). This should help

@ishubin I think we should at a Junit sample in the docs besides [TestNG](http://galenframework.com/docs/reference-java-tests/).

**Comment by JeffGaly** [comment]
Thanks for the reply .But My project is on Serenity BDD where My pages are inheriting page object .So Im trying to validate Layout in between my execution during the page load.It that is possible ?

Note :Its Galen works fine when i write a separate class for galen.During integration I wanna run my runner file but it should also need to pick galen method.

**Comment by JeffGaly** [comment]
Any update on this ???
