### ISSUE TITLE
Galen get CSS attribute not working in Firefox

### ISSUE THREAD

**Issue by Jiff21** [galenframework/galen#552]
***Description***
Parameterized test it seems to be getting empty values ("") for css attributes like padding and margin about half of the runs.
 
Firefox 57.0.4
Galen Framework
Version: 2.3.6
JavaScript executor: Rhino 1.7 release 5 2015 01 29
Platform: OS X 10.12.6
Selenium Standalone Server: 3.8.1
Galen Framework
Version: 2.3.6
JavaScript executor: Rhino 1.7 release 5 2015 01 29

But just saw warning on [CSS spec](http://galenframework.com/docs/reference-galen-spec-language-guide/#CSSProperties) discovered [near](http://galenframework.com/docs/reference-galen-spec-language-guide/#Near), [below, above](http://galenframework.com/docs/reference-galen-spec-language-guide/#BelowandAbove), [left-of and right-of](http://galenframework.com/docs/reference-galen-spec-language-guide/#LeftofandRightof)  specs, so will try moving to that way. If you need to position off the edge of the browser window try `inside screen 20px left` ([screen](http://galenframework.com/docs/reference-galen-spec-language-guide/#screen)).

Run in Firefox:
________________________________________________________________________________________________________

***google.gspec***

```
@objects
        share          xpath     //div[contains(@class, 'knowledge-panel')]//div/span


= Example Section =
    share:
        @on large_desktop, desktop, tablet, mobile
            css padding is "8px"
```

***individual.test***
```
@@ import settings.test
contact page on a ${tablet_name} device
    ${base_url}/search?q=galen  ${tablet_dimensions}
        wait 30s until exist "xpath: //div[contains(@class, 'knowledge-panel')]//div/span"
        wait 1s
        check google.gspec --include chrome,tablet
```

Will Fail:
```
= Example Section =
    share:
->      css padding is "8px"
->      :   "share" css property "padding" is "" but should be "8px"
```

Note: The first parameterized run seems to include `[GFX1-]: Receive IPC close with reason=AbnormalShutdown`

**Comment by Jiff21** [comment]
Just realized it's 50% of the time because I was defaulting to Chrome and it doesn't work in Firefox. 
Firefox 57.0.4
Galen Framework
Version: 2.3.6
JavaScript executor: Rhino 1.7 release 5 2015 01 29
Platform: OS X 10.12.6
Selenium Standalone Server: 3.8.1

But just saw warning on [CSS spec](http://galenframework.com/docs/reference-galen-spec-language-guide/#CSSProperties) discovered [near](http://galenframework.com/docs/reference-galen-spec-language-guide/#Near), [below, above](http://galenframework.com/docs/reference-galen-spec-language-guide/#BelowandAbove), [left-of and right-of](http://galenframework.com/docs/reference-galen-spec-language-guide/#LeftofandRightof)  specs, so will try moving to that way. If you're dealing with edge of screen what

**Comment by cyildirim** [comment]
Hi @Jiff21 ,

Can you share full log with us ?

**Comment by Jiff21** [comment]
Sure thing.

```
========================================
Test: contact page on a Tablet device
========================================
Jan 12, 2018 9:03:44 AM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
1515776625440	geckodriver	INFO	Listening on 127.0.0.1:2733
1515776625675	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
1515776626723	Marionette	INFO	Enabled via --marionette
2018-01-12 09:03:47.458 plugin-container[2437:31423] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xb233, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1515776627849	Marionette	INFO	Listening on port 49841
1515776627928	Marionette	WARN	TLS certificate errors will be ignored for this session
1515776627971	Marionette	DEBUG	Register listener.js for window 2147483649
Jan 12, 2018 9:03:48 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1515776628075	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1515776629378	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1515776629378	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1515776630212	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.google.com/search?q=galen"
1515776631792	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.google.com/search?q=galen"
wait 30s until exist "xpath: //div[contains(@class, 'knowledge-panel')]//div/span"
wait 1s
check google.gspec --include chrome,tablet
= Example Section =
    share:
->      css padding is "8px"
->      :   "share" css property "padding" is "" but should be "8px"

[GFX1-]: Receive IPC close with reason=AbnormalShutdown

```

**Comment by cyildirim** [comment]
This a bug of a geckodriver for padding attribute. You can create an issue to geckodriver.

I have run that script with Chrome and Firefox. Results are like that
```
➜  Desktop python testScript.py
chrome
6.4px 8px 4.8px
➜  Desktop python testScript.py
firefox
```

Sample script
```
driver = webdriver.Firefox()
driver.get("http://www.python.org")
print driver.name
elem = driver.find_element_by_id("id-search-field")
print elem.value_of_css_property("padding")
driver.close()
```


@ishubin please close.

**Comment by Jiff21** [comment]
See Geckodriver [#1130](https://github.com/mozilla/geckodriver/issues/1130)
