### ISSUE TITLE
SeleniumGrid and Check Report

### ISSUE THREAD

**Issue by mtopcu** [galenframework/galen#582]
Hi,
Is there any way to create html report for test cases running on SelenimuGrid. When I use                
 "--htmlreport reports", I got below failure.

```
Exception in thread "main" java.lang.RuntimeException: com.galenframework.parser.SyntaxException: Unknown argument: htmlreport
    in /Users/trtopcmu/galen/comparing/runtest.test:27
```

**Comment by ishubin** [comment]
Hi. `--htmlreport` argument is only supported from command line. It is a report of all the tests that you are running.
