### ISSUE TITLE
Galen 2.4.0 pagedump usage

### ISSUE THREAD

**Issue by satyasushmachopparapu** [galenframework/galen#609]
I'm trying to use pagedump feature to generate spec file automatically. I'm using 2.4.0 latest version of galen and the code looks like this.
  GalenPageDump dump=new GalenPageDump("http://gmail.com");     
        dump.dumpPage(driver,"C:/galen/pageDump/Specs/input.spec","C:/galen/pageDump/dumps/login");

**Error Details**
Exception in thread "main" com.galenframework.parser.SyntaxException: Unknown statement: base-js   id   base-js
    in C:/galen/pageDump/Specs/input.spec:3

Could anyone please help me here.

**Comment by vihoang0706** [comment]
> @satyasushmachopparapu No Page Dump does not generate rules anymore since of galen version 2.4. Instead there is now a spec generator in Galen which you should use instead http://galenframework.com/docs/reference-working-in-command-line/#SpecGenerator
> But you do need to create a page dump first because that one is used as a source for spec generator

Sorry guy, I have already applied your suggestions into my assignments, but it is still not working.
