### ISSUE TITLE
Show image comparison link is missing since 2.4.0

### ISSUE THREAD

**Issue by igor-dmitriev** [galenframework/galen#616]
I was trying to get an image comparison result with Galen 2.4.3, but the 'Show image comparison' button was missing. It works in 2.3.7. The feature has gone since 2.4.0 version.

**2.4.0**
<img width="976" alt="screen shot 2019-03-07 at 7 32 08 pm" src="https://user-images.githubusercontent.com/4592740/53976707-3cfce680-4110-11e9-9f1a-408919cbc2f5.png">

**2.3.7**
<img width="1039" alt="screen shot 2019-03-07 at 7 31 51 pm" src="https://user-images.githubusercontent.com/4592740/53976727-4423f480-4110-11e9-8a44-88bbb8575931.png">

**Comment by ishubin** [comment]
Thanks for reporting! I will try to fix over the weekend

**Comment by ishubin** [comment]
I have released a fix for it in version 2.4.4

**Comment by igor-dmitriev** [comment]
super fast, thank you for such a great tool
