### ISSUE TITLE
galenframework.com no longer valid? remove references within repo?

### ISSUE THREAD

**Issue by dsample** [galenframework/galen#666]
It seems the galenframework.com domain is no longer related to this repository, and instead a diagramming tool called Schemio. Deeper links now result in 404 errors.

Should references to the domain be removed from the repository and any documentation which was on that site be put into the github Wiki or other repo-based documentation?

**Comment by ishubin** [comment]
Oh, Schemio is hosted on the same server as galenframework.com. The galenframework.com does not supports http so it looks like the sever is not correctly configured. If you use http version it should work - http://galenframework.com

I will try to fix it

**Comment by ishubin** [comment]
Should be fixed now
