### ISSUE TITLE
Add shortcut spec LEFT and RIGHT

### ISSUE THREAD

**Issue by claytonneal** [galenframework/galen#84]
For above/below there is shortcut specs
However for LEFT and RIGHT the only spec is NEAR - which a Range is mandatory
It would be great just to be able to specif LEFT and RIGHT with no range..

**Comment by ishubin** [comment]
Sorry for late response. I think "left of" and "right of" makes sense, thanks for suggestions.  Will build it for release-1.6 or next one

**Comment by phystem** [comment]
You haven't added those two functions in galen-pagedump.js

**Comment by ishubin** [comment]
@phystem oops :) thanks for reminding that one. will fix it
