### ISSUE TITLE
Provide support for iframes

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#93]
At the moment it is not possible to get the location of elements within iframe and test them with Galen Specs.
My initial plan was to do something like this

```
===============================================================
some-object-inside-iframe     css #iframe  |  css a.title
===============================================================
```
Where the pipe symbol is an indicator that the previous "#iframe" is an iframe and the next "a.title" element is located within that iframe

But it might be the the syntax will be changed. I am still thinking what will work better as these frames should also be support by component section. Something to keep in mind when testing.

For components

```
============================================================
some-frame   css #iframe |
============================================================

some-frame
    component: some-component.spec
```

the problem is that pipe is used in CSS selectors so we still need to think through the proper syntax. So maybe something like this could work:

```
=============================================
some-element-inside-frame   frame "css #iframe" id button
=============================================
```

**Comment by ishubin** [comment]
Seems like it will be too complex to introduce the above syntax. Perhaps the easiest way would be to allow components to switch to frames like below:

```
===============
some-frame-component    css iframe.some-banner
===============

some-frame-component
    component frame: specs/banner.spec
```

**Comment by ishubin** [comment]
Implemented in release-1.5 branch

**Comment by susnigdha1** [comment]
Hi,
Could you please provide an example of how to handle iFrame,  using Galenframework + Java + TestNG ? 
 
Regards,
Susnigdha Chatterjee

**Comment by dhapolapankaj** [comment]
Hi @ishubin 
Can you provide some examples here?
This is with reference to #504

**Comment by ishubin** [comment]
I don't have any examples at the moment. It works in a simple way: when component switches to frame, then all of the elements defined in that component will be located only within that frame
